// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public interface DataFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bentoml.grpc.v1.DataFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @return A list containing the columnNames.
   */
  java.util.List<java.lang.String>
      getColumnNamesList();
  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @return The count of columnNames.
   */
  int getColumnNamesCount();
  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @param index The index of the element to return.
   * @return The columnNames at the given index.
   */
  java.lang.String getColumnNames(int index);
  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the columnNames at the given index.
   */
  com.google.protobuf.ByteString
      getColumnNamesBytes(int index);

  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  java.util.List<com.bentoml.grpc.v1.Series> 
      getColumnsList();
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  com.bentoml.grpc.v1.Series getColumns(int index);
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  int getColumnsCount();
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  java.util.List<? extends com.bentoml.grpc.v1.SeriesOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  com.bentoml.grpc.v1.SeriesOrBuilder getColumnsOrBuilder(
      int index);
}
