// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

/**
 * <pre>
 * DataFrame represents any tabular data type. We are using
 * DataFrame as a trivial representation for tabular type.
 * This message carries given implementation of tabular data based on given orientation.
 * TODO: support index, records, etc.
 * </pre>
 *
 * Protobuf type {@code bentoml.grpc.v1.DataFrame}
 */
public final class DataFrame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bentoml.grpc.v1.DataFrame)
    DataFrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataFrame.newBuilder() to construct.
  private DataFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataFrame() {
    columnNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    columns_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataFrame();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_DataFrame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_DataFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bentoml.grpc.v1.DataFrame.class, com.bentoml.grpc.v1.DataFrame.Builder.class);
  }

  public static final int COLUMN_NAMES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList columnNames_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @return A list containing the columnNames.
   */
  public com.google.protobuf.ProtocolStringList
      getColumnNamesList() {
    return columnNames_;
  }
  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @return The count of columnNames.
   */
  public int getColumnNamesCount() {
    return columnNames_.size();
  }
  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @param index The index of the element to return.
   * @return The columnNames at the given index.
   */
  public java.lang.String getColumnNames(int index) {
    return columnNames_.get(index);
  }
  /**
   * <pre>
   * columns name
   * </pre>
   *
   * <code>repeated string column_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the columnNames at the given index.
   */
  public com.google.protobuf.ByteString
      getColumnNamesBytes(int index) {
    return columnNames_.getByteString(index);
  }

  public static final int COLUMNS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.bentoml.grpc.v1.Series> columns_;
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.bentoml.grpc.v1.Series> getColumnsList() {
    return columns_;
  }
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bentoml.grpc.v1.SeriesOrBuilder> 
      getColumnsOrBuilderList() {
    return columns_;
  }
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  @java.lang.Override
  public int getColumnsCount() {
    return columns_.size();
  }
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.Series getColumns(int index) {
    return columns_.get(index);
  }
  /**
   * <pre>
   * columns orient.
   * { column ↠ { index ↠ value } }
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.SeriesOrBuilder getColumnsOrBuilder(
      int index) {
    return columns_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < columnNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, columnNames_.getRaw(i));
    }
    for (int i = 0; i < columns_.size(); i++) {
      output.writeMessage(2, columns_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < columnNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(columnNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getColumnNamesList().size();
    }
    for (int i = 0; i < columns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, columns_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bentoml.grpc.v1.DataFrame)) {
      return super.equals(obj);
    }
    com.bentoml.grpc.v1.DataFrame other = (com.bentoml.grpc.v1.DataFrame) obj;

    if (!getColumnNamesList()
        .equals(other.getColumnNamesList())) return false;
    if (!getColumnsList()
        .equals(other.getColumnsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getColumnNamesCount() > 0) {
      hash = (37 * hash) + COLUMN_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getColumnNamesList().hashCode();
    }
    if (getColumnsCount() > 0) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bentoml.grpc.v1.DataFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bentoml.grpc.v1.DataFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.DataFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bentoml.grpc.v1.DataFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * This message carries given implementation of tabular data based on given orientation.
   * TODO: support index, records, etc.
   * </pre>
   *
   * Protobuf type {@code bentoml.grpc.v1.DataFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bentoml.grpc.v1.DataFrame)
      com.bentoml.grpc.v1.DataFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_DataFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_DataFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bentoml.grpc.v1.DataFrame.class, com.bentoml.grpc.v1.DataFrame.Builder.class);
    }

    // Construct using com.bentoml.grpc.v1.DataFrame.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      columnNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
      } else {
        columns_ = null;
        columnsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_DataFrame_descriptor;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.DataFrame getDefaultInstanceForType() {
      return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.DataFrame build() {
      com.bentoml.grpc.v1.DataFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.DataFrame buildPartial() {
      com.bentoml.grpc.v1.DataFrame result = new com.bentoml.grpc.v1.DataFrame(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bentoml.grpc.v1.DataFrame result) {
      if (columnsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          columns_ = java.util.Collections.unmodifiableList(columns_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.columns_ = columns_;
      } else {
        result.columns_ = columnsBuilder_.build();
      }
    }

    private void buildPartial0(com.bentoml.grpc.v1.DataFrame result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        columnNames_.makeImmutable();
        result.columnNames_ = columnNames_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bentoml.grpc.v1.DataFrame) {
        return mergeFrom((com.bentoml.grpc.v1.DataFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bentoml.grpc.v1.DataFrame other) {
      if (other == com.bentoml.grpc.v1.DataFrame.getDefaultInstance()) return this;
      if (!other.columnNames_.isEmpty()) {
        if (columnNames_.isEmpty()) {
          columnNames_ = other.columnNames_;
          bitField0_ |= 0x00000001;
        } else {
          ensureColumnNamesIsMutable();
          columnNames_.addAll(other.columnNames_);
        }
        onChanged();
      }
      if (columnsBuilder_ == null) {
        if (!other.columns_.isEmpty()) {
          if (columns_.isEmpty()) {
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureColumnsIsMutable();
            columns_.addAll(other.columns_);
          }
          onChanged();
        }
      } else {
        if (!other.columns_.isEmpty()) {
          if (columnsBuilder_.isEmpty()) {
            columnsBuilder_.dispose();
            columnsBuilder_ = null;
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000002);
            columnsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColumnsFieldBuilder() : null;
          } else {
            columnsBuilder_.addAllMessages(other.columns_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureColumnNamesIsMutable();
              columnNames_.add(s);
              break;
            } // case 10
            case 18: {
              com.bentoml.grpc.v1.Series m =
                  input.readMessage(
                      com.bentoml.grpc.v1.Series.parser(),
                      extensionRegistry);
              if (columnsBuilder_ == null) {
                ensureColumnsIsMutable();
                columns_.add(m);
              } else {
                columnsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList columnNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureColumnNamesIsMutable() {
      if (!columnNames_.isModifiable()) {
        columnNames_ = new com.google.protobuf.LazyStringArrayList(columnNames_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @return A list containing the columnNames.
     */
    public com.google.protobuf.ProtocolStringList
        getColumnNamesList() {
      columnNames_.makeImmutable();
      return columnNames_;
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @return The count of columnNames.
     */
    public int getColumnNamesCount() {
      return columnNames_.size();
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @param index The index of the element to return.
     * @return The columnNames at the given index.
     */
    public java.lang.String getColumnNames(int index) {
      return columnNames_.get(index);
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the columnNames at the given index.
     */
    public com.google.protobuf.ByteString
        getColumnNamesBytes(int index) {
      return columnNames_.getByteString(index);
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @param index The index to set the value at.
     * @param value The columnNames to set.
     * @return This builder for chaining.
     */
    public Builder setColumnNames(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureColumnNamesIsMutable();
      columnNames_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @param value The columnNames to add.
     * @return This builder for chaining.
     */
    public Builder addColumnNames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureColumnNamesIsMutable();
      columnNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @param values The columnNames to add.
     * @return This builder for chaining.
     */
    public Builder addAllColumnNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureColumnNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, columnNames_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearColumnNames() {
      columnNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * columns name
     * </pre>
     *
     * <code>repeated string column_names = 1;</code>
     * @param value The bytes of the columnNames to add.
     * @return This builder for chaining.
     */
    public Builder addColumnNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureColumnNamesIsMutable();
      columnNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.bentoml.grpc.v1.Series> columns_ =
      java.util.Collections.emptyList();
    private void ensureColumnsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        columns_ = new java.util.ArrayList<com.bentoml.grpc.v1.Series>(columns_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder> columnsBuilder_;

    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public java.util.List<com.bentoml.grpc.v1.Series> getColumnsList() {
      if (columnsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(columns_);
      } else {
        return columnsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public int getColumnsCount() {
      if (columnsBuilder_ == null) {
        return columns_.size();
      } else {
        return columnsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public com.bentoml.grpc.v1.Series getColumns(int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);
      } else {
        return columnsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder setColumns(
        int index, com.bentoml.grpc.v1.Series value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.set(index, value);
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder setColumns(
        int index, com.bentoml.grpc.v1.Series.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.set(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder addColumns(com.bentoml.grpc.v1.Series value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder addColumns(
        int index, com.bentoml.grpc.v1.Series value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(index, value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder addColumns(
        com.bentoml.grpc.v1.Series.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder addColumns(
        int index, com.bentoml.grpc.v1.Series.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder addAllColumns(
        java.lang.Iterable<? extends com.bentoml.grpc.v1.Series> values) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columns_);
        onChanged();
      } else {
        columnsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder clearColumns() {
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        columnsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public Builder removeColumns(int index) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.remove(index);
        onChanged();
      } else {
        columnsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public com.bentoml.grpc.v1.Series.Builder getColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public com.bentoml.grpc.v1.SeriesOrBuilder getColumnsOrBuilder(
        int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);  } else {
        return columnsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public java.util.List<? extends com.bentoml.grpc.v1.SeriesOrBuilder> 
         getColumnsOrBuilderList() {
      if (columnsBuilder_ != null) {
        return columnsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(columns_);
      }
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public com.bentoml.grpc.v1.Series.Builder addColumnsBuilder() {
      return getColumnsFieldBuilder().addBuilder(
          com.bentoml.grpc.v1.Series.getDefaultInstance());
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public com.bentoml.grpc.v1.Series.Builder addColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().addBuilder(
          index, com.bentoml.grpc.v1.Series.getDefaultInstance());
    }
    /**
     * <pre>
     * columns orient.
     * { column ↠ { index ↠ value } }
     * </pre>
     *
     * <code>repeated .bentoml.grpc.v1.Series columns = 2;</code>
     */
    public java.util.List<com.bentoml.grpc.v1.Series.Builder> 
         getColumnsBuilderList() {
      return getColumnsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder> 
        getColumnsFieldBuilder() {
      if (columnsBuilder_ == null) {
        columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder>(
                columns_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        columns_ = null;
      }
      return columnsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bentoml.grpc.v1.DataFrame)
  }

  // @@protoc_insertion_point(class_scope:bentoml.grpc.v1.DataFrame)
  private static final com.bentoml.grpc.v1.DataFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bentoml.grpc.v1.DataFrame();
  }

  public static com.bentoml.grpc.v1.DataFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataFrame>
      PARSER = new com.google.protobuf.AbstractParser<DataFrame>() {
    @java.lang.Override
    public DataFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataFrame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataFrame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bentoml.grpc.v1.DataFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

