// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public interface FileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bentoml.grpc.v1.File)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * optional file type, let it be csv, text, parquet, etc.
   * v1alpha1 uses 1 as FileType enum.
   * </pre>
   *
   * <code>optional string kind = 3;</code>
   * @return Whether the kind field is set.
   */
  boolean hasKind();
  /**
   * <pre>
   * optional file type, let it be csv, text, parquet, etc.
   * v1alpha1 uses 1 as FileType enum.
   * </pre>
   *
   * <code>optional string kind = 3;</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <pre>
   * optional file type, let it be csv, text, parquet, etc.
   * v1alpha1 uses 1 as FileType enum.
   * </pre>
   *
   * <code>optional string kind = 3;</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <pre>
   * contents of file as bytes.
   * </pre>
   *
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
