// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public interface MultipartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bentoml.grpc.v1.Multipart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  boolean containsFields(
      java.lang.String key);
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part>
  getFields();
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part>
  getFieldsMap();
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  /* nullable */
com.bentoml.grpc.v1.Part getFieldsOrDefault(
      java.lang.String key,
      /* nullable */
com.bentoml.grpc.v1.Part defaultValue);
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  com.bentoml.grpc.v1.Part getFieldsOrThrow(
      java.lang.String key);
}
