// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

/**
 * <pre>
 * Multipart represents a multipart message.
 * It comprises of a mapping from given type name to a subset of aforementioned types.
 * </pre>
 *
 * Protobuf type {@code bentoml.grpc.v1.Multipart}
 */
public final class Multipart extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bentoml.grpc.v1.Multipart)
    MultipartOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Multipart.newBuilder() to construct.
  private Multipart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Multipart() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Multipart();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Multipart_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetFields();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Multipart_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bentoml.grpc.v1.Multipart.class, com.bentoml.grpc.v1.Multipart.Builder.class);
  }

  public static final int FIELDS_FIELD_NUMBER = 1;
  private static final class FieldsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.bentoml.grpc.v1.Part> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.bentoml.grpc.v1.Part>newDefaultInstance(
                com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Multipart_FieldsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.bentoml.grpc.v1.Part.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.bentoml.grpc.v1.Part> fields_;
  private com.google.protobuf.MapField<java.lang.String, com.bentoml.grpc.v1.Part>
  internalGetFields() {
    if (fields_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FieldsDefaultEntryHolder.defaultEntry);
    }
    return fields_;
  }
  public int getFieldsCount() {
    return internalGetFields().getMap().size();
  }
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  @java.lang.Override
  public boolean containsFields(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFields().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> getFields() {
    return getFieldsMap();
  }
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> getFieldsMap() {
    return internalGetFields().getMap();
  }
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
com.bentoml.grpc.v1.Part getFieldsOrDefault(
      java.lang.String key,
      /* nullable */
com.bentoml.grpc.v1.Part defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> map =
        internalGetFields().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.Part getFieldsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> map =
        internalGetFields().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFields(),
        FieldsDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.bentoml.grpc.v1.Part> entry
         : internalGetFields().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.bentoml.grpc.v1.Part>
      fields__ = FieldsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fields__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bentoml.grpc.v1.Multipart)) {
      return super.equals(obj);
    }
    com.bentoml.grpc.v1.Multipart other = (com.bentoml.grpc.v1.Multipart) obj;

    if (!internalGetFields().equals(
        other.internalGetFields())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetFields().getMap().isEmpty()) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFields().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bentoml.grpc.v1.Multipart parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bentoml.grpc.v1.Multipart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bentoml.grpc.v1.Multipart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Multipart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bentoml.grpc.v1.Multipart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Multipart represents a multipart message.
   * It comprises of a mapping from given type name to a subset of aforementioned types.
   * </pre>
   *
   * Protobuf type {@code bentoml.grpc.v1.Multipart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bentoml.grpc.v1.Multipart)
      com.bentoml.grpc.v1.MultipartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Multipart_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Multipart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bentoml.grpc.v1.Multipart.class, com.bentoml.grpc.v1.Multipart.Builder.class);
    }

    // Construct using com.bentoml.grpc.v1.Multipart.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableFields().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Multipart_descriptor;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Multipart getDefaultInstanceForType() {
      return com.bentoml.grpc.v1.Multipart.getDefaultInstance();
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Multipart build() {
      com.bentoml.grpc.v1.Multipart result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Multipart buildPartial() {
      com.bentoml.grpc.v1.Multipart result = new com.bentoml.grpc.v1.Multipart(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bentoml.grpc.v1.Multipart result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fields_ = internalGetFields();
        result.fields_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bentoml.grpc.v1.Multipart) {
        return mergeFrom((com.bentoml.grpc.v1.Multipart)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bentoml.grpc.v1.Multipart other) {
      if (other == com.bentoml.grpc.v1.Multipart.getDefaultInstance()) return this;
      internalGetMutableFields().mergeFrom(
          other.internalGetFields());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.bentoml.grpc.v1.Part>
              fields__ = input.readMessage(
                  FieldsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableFields().getMutableMap().put(
                  fields__.getKey(), fields__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.bentoml.grpc.v1.Part> fields_;
    private com.google.protobuf.MapField<java.lang.String, com.bentoml.grpc.v1.Part>
        internalGetFields() {
      if (fields_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FieldsDefaultEntryHolder.defaultEntry);
      }
      return fields_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.bentoml.grpc.v1.Part>
        internalGetMutableFields() {
      if (fields_ == null) {
        fields_ = com.google.protobuf.MapField.newMapField(
            FieldsDefaultEntryHolder.defaultEntry);
      }
      if (!fields_.isMutable()) {
        fields_ = fields_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return fields_;
    }
    public int getFieldsCount() {
      return internalGetFields().getMap().size();
    }
    /**
     * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
     */
    @java.lang.Override
    public boolean containsFields(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFields().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFieldsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> getFields() {
      return getFieldsMap();
    }
    /**
     * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> getFieldsMap() {
      return internalGetFields().getMap();
    }
    /**
     * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.bentoml.grpc.v1.Part getFieldsOrDefault(
        java.lang.String key,
        /* nullable */
com.bentoml.grpc.v1.Part defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> map =
          internalGetFields().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.Part getFieldsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> map =
          internalGetFields().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearFields() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableFields().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
     */
    public Builder removeFields(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFields().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part>
        getMutableFields() {
      bitField0_ |= 0x00000001;
      return internalGetMutableFields().getMutableMap();
    }
    /**
     * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
     */
    public Builder putFields(
        java.lang.String key,
        com.bentoml.grpc.v1.Part value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableFields().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .bentoml.grpc.v1.Part&gt; fields = 1;</code>
     */
    public Builder putAllFields(
        java.util.Map<java.lang.String, com.bentoml.grpc.v1.Part> values) {
      internalGetMutableFields().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bentoml.grpc.v1.Multipart)
  }

  // @@protoc_insertion_point(class_scope:bentoml.grpc.v1.Multipart)
  private static final com.bentoml.grpc.v1.Multipart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bentoml.grpc.v1.Multipart();
  }

  public static com.bentoml.grpc.v1.Multipart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Multipart>
      PARSER = new com.google.protobuf.AbstractParser<Multipart>() {
    @java.lang.Override
    public Multipart parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Multipart> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Multipart> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bentoml.grpc.v1.Multipart getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

