// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

/**
 * <pre>
 * Part represents possible value types for multipart message.
 * These are the same as the types in Request message.
 * </pre>
 *
 * Protobuf type {@code bentoml.grpc.v1.Part}
 */
public final class Part extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bentoml.grpc.v1.Part)
    PartOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Part.newBuilder() to construct.
  private Part(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Part() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Part();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Part_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Part_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bentoml.grpc.v1.Part.class, com.bentoml.grpc.v1.Part.Builder.class);
  }

  private int representationCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object representation_;
  public enum RepresentationCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NDARRAY(1),
    DATAFRAME(3),
    SERIES(5),
    FILE(6),
    TEXT(7),
    JSON(8),
    SERIALIZED_BYTES(4),
    REPRESENTATION_NOT_SET(0);
    private final int value;
    private RepresentationCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RepresentationCase valueOf(int value) {
      return forNumber(value);
    }

    public static RepresentationCase forNumber(int value) {
      switch (value) {
        case 1: return NDARRAY;
        case 3: return DATAFRAME;
        case 5: return SERIES;
        case 6: return FILE;
        case 7: return TEXT;
        case 8: return JSON;
        case 4: return SERIALIZED_BYTES;
        case 0: return REPRESENTATION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RepresentationCase
  getRepresentationCase() {
    return RepresentationCase.forNumber(
        representationCase_);
  }

  public static final int NDARRAY_FIELD_NUMBER = 1;
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   * @return Whether the ndarray field is set.
   */
  @java.lang.Override
  public boolean hasNdarray() {
    return representationCase_ == 1;
  }
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   * @return The ndarray.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.NDArray getNdarray() {
    if (representationCase_ == 1) {
       return (com.bentoml.grpc.v1.NDArray) representation_;
    }
    return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
  }
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.NDArrayOrBuilder getNdarrayOrBuilder() {
    if (representationCase_ == 1) {
       return (com.bentoml.grpc.v1.NDArray) representation_;
    }
    return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
  }

  public static final int DATAFRAME_FIELD_NUMBER = 3;
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   * @return Whether the dataframe field is set.
   */
  @java.lang.Override
  public boolean hasDataframe() {
    return representationCase_ == 3;
  }
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   * @return The dataframe.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.DataFrame getDataframe() {
    if (representationCase_ == 3) {
       return (com.bentoml.grpc.v1.DataFrame) representation_;
    }
    return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
  }
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.DataFrameOrBuilder getDataframeOrBuilder() {
    if (representationCase_ == 3) {
       return (com.bentoml.grpc.v1.DataFrame) representation_;
    }
    return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
  }

  public static final int SERIES_FIELD_NUMBER = 5;
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   * @return Whether the series field is set.
   */
  @java.lang.Override
  public boolean hasSeries() {
    return representationCase_ == 5;
  }
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   * @return The series.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.Series getSeries() {
    if (representationCase_ == 5) {
       return (com.bentoml.grpc.v1.Series) representation_;
    }
    return com.bentoml.grpc.v1.Series.getDefaultInstance();
  }
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.SeriesOrBuilder getSeriesOrBuilder() {
    if (representationCase_ == 5) {
       return (com.bentoml.grpc.v1.Series) representation_;
    }
    return com.bentoml.grpc.v1.Series.getDefaultInstance();
  }

  public static final int FILE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return representationCase_ == 6;
  }
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   * @return The file.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.File getFile() {
    if (representationCase_ == 6) {
       return (com.bentoml.grpc.v1.File) representation_;
    }
    return com.bentoml.grpc.v1.File.getDefaultInstance();
  }
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.FileOrBuilder getFileOrBuilder() {
    if (representationCase_ == 6) {
       return (com.bentoml.grpc.v1.File) representation_;
    }
    return com.bentoml.grpc.v1.File.getDefaultInstance();
  }

  public static final int TEXT_FIELD_NUMBER = 7;
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   * @return Whether the text field is set.
   */
  @java.lang.Override
  public boolean hasText() {
    return representationCase_ == 7;
  }
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   * @return The text.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getText() {
    if (representationCase_ == 7) {
       return (com.google.protobuf.StringValue) representation_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getTextOrBuilder() {
    if (representationCase_ == 7) {
       return (com.google.protobuf.StringValue) representation_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }

  public static final int JSON_FIELD_NUMBER = 8;
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   * @return Whether the json field is set.
   */
  @java.lang.Override
  public boolean hasJson() {
    return representationCase_ == 8;
  }
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   * @return The json.
   */
  @java.lang.Override
  public com.google.protobuf.Value getJson() {
    if (representationCase_ == 8) {
       return (com.google.protobuf.Value) representation_;
    }
    return com.google.protobuf.Value.getDefaultInstance();
  }
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ValueOrBuilder getJsonOrBuilder() {
    if (representationCase_ == 8) {
       return (com.google.protobuf.Value) representation_;
    }
    return com.google.protobuf.Value.getDefaultInstance();
  }

  public static final int SERIALIZED_BYTES_FIELD_NUMBER = 4;
  /**
   * <pre>
   * serialized_bytes is for data serialized in BentoML's internal serialization format.
   * </pre>
   *
   * <code>bytes serialized_bytes = 4;</code>
   * @return Whether the serializedBytes field is set.
   */
  @java.lang.Override
  public boolean hasSerializedBytes() {
    return representationCase_ == 4;
  }
  /**
   * <pre>
   * serialized_bytes is for data serialized in BentoML's internal serialization format.
   * </pre>
   *
   * <code>bytes serialized_bytes = 4;</code>
   * @return The serializedBytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSerializedBytes() {
    if (representationCase_ == 4) {
      return (com.google.protobuf.ByteString) representation_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (representationCase_ == 1) {
      output.writeMessage(1, (com.bentoml.grpc.v1.NDArray) representation_);
    }
    if (representationCase_ == 3) {
      output.writeMessage(3, (com.bentoml.grpc.v1.DataFrame) representation_);
    }
    if (representationCase_ == 4) {
      output.writeBytes(
          4, (com.google.protobuf.ByteString) representation_);
    }
    if (representationCase_ == 5) {
      output.writeMessage(5, (com.bentoml.grpc.v1.Series) representation_);
    }
    if (representationCase_ == 6) {
      output.writeMessage(6, (com.bentoml.grpc.v1.File) representation_);
    }
    if (representationCase_ == 7) {
      output.writeMessage(7, (com.google.protobuf.StringValue) representation_);
    }
    if (representationCase_ == 8) {
      output.writeMessage(8, (com.google.protobuf.Value) representation_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (representationCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.bentoml.grpc.v1.NDArray) representation_);
    }
    if (representationCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.bentoml.grpc.v1.DataFrame) representation_);
    }
    if (representationCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            4, (com.google.protobuf.ByteString) representation_);
    }
    if (representationCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.bentoml.grpc.v1.Series) representation_);
    }
    if (representationCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.bentoml.grpc.v1.File) representation_);
    }
    if (representationCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.google.protobuf.StringValue) representation_);
    }
    if (representationCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.google.protobuf.Value) representation_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bentoml.grpc.v1.Part)) {
      return super.equals(obj);
    }
    com.bentoml.grpc.v1.Part other = (com.bentoml.grpc.v1.Part) obj;

    if (!getRepresentationCase().equals(other.getRepresentationCase())) return false;
    switch (representationCase_) {
      case 1:
        if (!getNdarray()
            .equals(other.getNdarray())) return false;
        break;
      case 3:
        if (!getDataframe()
            .equals(other.getDataframe())) return false;
        break;
      case 5:
        if (!getSeries()
            .equals(other.getSeries())) return false;
        break;
      case 6:
        if (!getFile()
            .equals(other.getFile())) return false;
        break;
      case 7:
        if (!getText()
            .equals(other.getText())) return false;
        break;
      case 8:
        if (!getJson()
            .equals(other.getJson())) return false;
        break;
      case 4:
        if (!getSerializedBytes()
            .equals(other.getSerializedBytes())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (representationCase_) {
      case 1:
        hash = (37 * hash) + NDARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getNdarray().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DATAFRAME_FIELD_NUMBER;
        hash = (53 * hash) + getDataframe().hashCode();
        break;
      case 5:
        hash = (37 * hash) + SERIES_FIELD_NUMBER;
        hash = (53 * hash) + getSeries().hashCode();
        break;
      case 6:
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
        break;
      case 7:
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        break;
      case 8:
        hash = (37 * hash) + JSON_FIELD_NUMBER;
        hash = (53 * hash) + getJson().hashCode();
        break;
      case 4:
        hash = (37 * hash) + SERIALIZED_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getSerializedBytes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bentoml.grpc.v1.Part parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bentoml.grpc.v1.Part parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bentoml.grpc.v1.Part parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Part parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bentoml.grpc.v1.Part prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Part represents possible value types for multipart message.
   * These are the same as the types in Request message.
   * </pre>
   *
   * Protobuf type {@code bentoml.grpc.v1.Part}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bentoml.grpc.v1.Part)
      com.bentoml.grpc.v1.PartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Part_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Part_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bentoml.grpc.v1.Part.class, com.bentoml.grpc.v1.Part.Builder.class);
    }

    // Construct using com.bentoml.grpc.v1.Part.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (ndarrayBuilder_ != null) {
        ndarrayBuilder_.clear();
      }
      if (dataframeBuilder_ != null) {
        dataframeBuilder_.clear();
      }
      if (seriesBuilder_ != null) {
        seriesBuilder_.clear();
      }
      if (fileBuilder_ != null) {
        fileBuilder_.clear();
      }
      if (textBuilder_ != null) {
        textBuilder_.clear();
      }
      if (jsonBuilder_ != null) {
        jsonBuilder_.clear();
      }
      representationCase_ = 0;
      representation_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Part_descriptor;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Part getDefaultInstanceForType() {
      return com.bentoml.grpc.v1.Part.getDefaultInstance();
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Part build() {
      com.bentoml.grpc.v1.Part result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Part buildPartial() {
      com.bentoml.grpc.v1.Part result = new com.bentoml.grpc.v1.Part(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bentoml.grpc.v1.Part result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.bentoml.grpc.v1.Part result) {
      result.representationCase_ = representationCase_;
      result.representation_ = this.representation_;
      if (representationCase_ == 1 &&
          ndarrayBuilder_ != null) {
        result.representation_ = ndarrayBuilder_.build();
      }
      if (representationCase_ == 3 &&
          dataframeBuilder_ != null) {
        result.representation_ = dataframeBuilder_.build();
      }
      if (representationCase_ == 5 &&
          seriesBuilder_ != null) {
        result.representation_ = seriesBuilder_.build();
      }
      if (representationCase_ == 6 &&
          fileBuilder_ != null) {
        result.representation_ = fileBuilder_.build();
      }
      if (representationCase_ == 7 &&
          textBuilder_ != null) {
        result.representation_ = textBuilder_.build();
      }
      if (representationCase_ == 8 &&
          jsonBuilder_ != null) {
        result.representation_ = jsonBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bentoml.grpc.v1.Part) {
        return mergeFrom((com.bentoml.grpc.v1.Part)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bentoml.grpc.v1.Part other) {
      if (other == com.bentoml.grpc.v1.Part.getDefaultInstance()) return this;
      switch (other.getRepresentationCase()) {
        case NDARRAY: {
          mergeNdarray(other.getNdarray());
          break;
        }
        case DATAFRAME: {
          mergeDataframe(other.getDataframe());
          break;
        }
        case SERIES: {
          mergeSeries(other.getSeries());
          break;
        }
        case FILE: {
          mergeFile(other.getFile());
          break;
        }
        case TEXT: {
          mergeText(other.getText());
          break;
        }
        case JSON: {
          mergeJson(other.getJson());
          break;
        }
        case SERIALIZED_BYTES: {
          setSerializedBytes(other.getSerializedBytes());
          break;
        }
        case REPRESENTATION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getNdarrayFieldBuilder().getBuilder(),
                  extensionRegistry);
              representationCase_ = 1;
              break;
            } // case 10
            case 26: {
              input.readMessage(
                  getDataframeFieldBuilder().getBuilder(),
                  extensionRegistry);
              representationCase_ = 3;
              break;
            } // case 26
            case 34: {
              representation_ = input.readBytes();
              representationCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getSeriesFieldBuilder().getBuilder(),
                  extensionRegistry);
              representationCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getFileFieldBuilder().getBuilder(),
                  extensionRegistry);
              representationCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              representationCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getJsonFieldBuilder().getBuilder(),
                  extensionRegistry);
              representationCase_ = 8;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int representationCase_ = 0;
    private java.lang.Object representation_;
    public RepresentationCase
        getRepresentationCase() {
      return RepresentationCase.forNumber(
          representationCase_);
    }

    public Builder clearRepresentation() {
      representationCase_ = 0;
      representation_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.NDArray, com.bentoml.grpc.v1.NDArray.Builder, com.bentoml.grpc.v1.NDArrayOrBuilder> ndarrayBuilder_;
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     * @return Whether the ndarray field is set.
     */
    @java.lang.Override
    public boolean hasNdarray() {
      return representationCase_ == 1;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     * @return The ndarray.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.NDArray getNdarray() {
      if (ndarrayBuilder_ == null) {
        if (representationCase_ == 1) {
          return (com.bentoml.grpc.v1.NDArray) representation_;
        }
        return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
      } else {
        if (representationCase_ == 1) {
          return ndarrayBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder setNdarray(com.bentoml.grpc.v1.NDArray value) {
      if (ndarrayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        representation_ = value;
        onChanged();
      } else {
        ndarrayBuilder_.setMessage(value);
      }
      representationCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder setNdarray(
        com.bentoml.grpc.v1.NDArray.Builder builderForValue) {
      if (ndarrayBuilder_ == null) {
        representation_ = builderForValue.build();
        onChanged();
      } else {
        ndarrayBuilder_.setMessage(builderForValue.build());
      }
      representationCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder mergeNdarray(com.bentoml.grpc.v1.NDArray value) {
      if (ndarrayBuilder_ == null) {
        if (representationCase_ == 1 &&
            representation_ != com.bentoml.grpc.v1.NDArray.getDefaultInstance()) {
          representation_ = com.bentoml.grpc.v1.NDArray.newBuilder((com.bentoml.grpc.v1.NDArray) representation_)
              .mergeFrom(value).buildPartial();
        } else {
          representation_ = value;
        }
        onChanged();
      } else {
        if (representationCase_ == 1) {
          ndarrayBuilder_.mergeFrom(value);
        } else {
          ndarrayBuilder_.setMessage(value);
        }
      }
      representationCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder clearNdarray() {
      if (ndarrayBuilder_ == null) {
        if (representationCase_ == 1) {
          representationCase_ = 0;
          representation_ = null;
          onChanged();
        }
      } else {
        if (representationCase_ == 1) {
          representationCase_ = 0;
          representation_ = null;
        }
        ndarrayBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public com.bentoml.grpc.v1.NDArray.Builder getNdarrayBuilder() {
      return getNdarrayFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.NDArrayOrBuilder getNdarrayOrBuilder() {
      if ((representationCase_ == 1) && (ndarrayBuilder_ != null)) {
        return ndarrayBuilder_.getMessageOrBuilder();
      } else {
        if (representationCase_ == 1) {
          return (com.bentoml.grpc.v1.NDArray) representation_;
        }
        return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.NDArray, com.bentoml.grpc.v1.NDArray.Builder, com.bentoml.grpc.v1.NDArrayOrBuilder> 
        getNdarrayFieldBuilder() {
      if (ndarrayBuilder_ == null) {
        if (!(representationCase_ == 1)) {
          representation_ = com.bentoml.grpc.v1.NDArray.getDefaultInstance();
        }
        ndarrayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.NDArray, com.bentoml.grpc.v1.NDArray.Builder, com.bentoml.grpc.v1.NDArrayOrBuilder>(
                (com.bentoml.grpc.v1.NDArray) representation_,
                getParentForChildren(),
                isClean());
        representation_ = null;
      }
      representationCase_ = 1;
      onChanged();
      return ndarrayBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.DataFrame, com.bentoml.grpc.v1.DataFrame.Builder, com.bentoml.grpc.v1.DataFrameOrBuilder> dataframeBuilder_;
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     * @return Whether the dataframe field is set.
     */
    @java.lang.Override
    public boolean hasDataframe() {
      return representationCase_ == 3;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     * @return The dataframe.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.DataFrame getDataframe() {
      if (dataframeBuilder_ == null) {
        if (representationCase_ == 3) {
          return (com.bentoml.grpc.v1.DataFrame) representation_;
        }
        return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
      } else {
        if (representationCase_ == 3) {
          return dataframeBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder setDataframe(com.bentoml.grpc.v1.DataFrame value) {
      if (dataframeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        representation_ = value;
        onChanged();
      } else {
        dataframeBuilder_.setMessage(value);
      }
      representationCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder setDataframe(
        com.bentoml.grpc.v1.DataFrame.Builder builderForValue) {
      if (dataframeBuilder_ == null) {
        representation_ = builderForValue.build();
        onChanged();
      } else {
        dataframeBuilder_.setMessage(builderForValue.build());
      }
      representationCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder mergeDataframe(com.bentoml.grpc.v1.DataFrame value) {
      if (dataframeBuilder_ == null) {
        if (representationCase_ == 3 &&
            representation_ != com.bentoml.grpc.v1.DataFrame.getDefaultInstance()) {
          representation_ = com.bentoml.grpc.v1.DataFrame.newBuilder((com.bentoml.grpc.v1.DataFrame) representation_)
              .mergeFrom(value).buildPartial();
        } else {
          representation_ = value;
        }
        onChanged();
      } else {
        if (representationCase_ == 3) {
          dataframeBuilder_.mergeFrom(value);
        } else {
          dataframeBuilder_.setMessage(value);
        }
      }
      representationCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder clearDataframe() {
      if (dataframeBuilder_ == null) {
        if (representationCase_ == 3) {
          representationCase_ = 0;
          representation_ = null;
          onChanged();
        }
      } else {
        if (representationCase_ == 3) {
          representationCase_ = 0;
          representation_ = null;
        }
        dataframeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public com.bentoml.grpc.v1.DataFrame.Builder getDataframeBuilder() {
      return getDataframeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.DataFrameOrBuilder getDataframeOrBuilder() {
      if ((representationCase_ == 3) && (dataframeBuilder_ != null)) {
        return dataframeBuilder_.getMessageOrBuilder();
      } else {
        if (representationCase_ == 3) {
          return (com.bentoml.grpc.v1.DataFrame) representation_;
        }
        return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.DataFrame, com.bentoml.grpc.v1.DataFrame.Builder, com.bentoml.grpc.v1.DataFrameOrBuilder> 
        getDataframeFieldBuilder() {
      if (dataframeBuilder_ == null) {
        if (!(representationCase_ == 3)) {
          representation_ = com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
        }
        dataframeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.DataFrame, com.bentoml.grpc.v1.DataFrame.Builder, com.bentoml.grpc.v1.DataFrameOrBuilder>(
                (com.bentoml.grpc.v1.DataFrame) representation_,
                getParentForChildren(),
                isClean());
        representation_ = null;
      }
      representationCase_ = 3;
      onChanged();
      return dataframeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder> seriesBuilder_;
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     * @return Whether the series field is set.
     */
    @java.lang.Override
    public boolean hasSeries() {
      return representationCase_ == 5;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     * @return The series.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.Series getSeries() {
      if (seriesBuilder_ == null) {
        if (representationCase_ == 5) {
          return (com.bentoml.grpc.v1.Series) representation_;
        }
        return com.bentoml.grpc.v1.Series.getDefaultInstance();
      } else {
        if (representationCase_ == 5) {
          return seriesBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.Series.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder setSeries(com.bentoml.grpc.v1.Series value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        representation_ = value;
        onChanged();
      } else {
        seriesBuilder_.setMessage(value);
      }
      representationCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder setSeries(
        com.bentoml.grpc.v1.Series.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        representation_ = builderForValue.build();
        onChanged();
      } else {
        seriesBuilder_.setMessage(builderForValue.build());
      }
      representationCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder mergeSeries(com.bentoml.grpc.v1.Series value) {
      if (seriesBuilder_ == null) {
        if (representationCase_ == 5 &&
            representation_ != com.bentoml.grpc.v1.Series.getDefaultInstance()) {
          representation_ = com.bentoml.grpc.v1.Series.newBuilder((com.bentoml.grpc.v1.Series) representation_)
              .mergeFrom(value).buildPartial();
        } else {
          representation_ = value;
        }
        onChanged();
      } else {
        if (representationCase_ == 5) {
          seriesBuilder_.mergeFrom(value);
        } else {
          seriesBuilder_.setMessage(value);
        }
      }
      representationCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder clearSeries() {
      if (seriesBuilder_ == null) {
        if (representationCase_ == 5) {
          representationCase_ = 0;
          representation_ = null;
          onChanged();
        }
      } else {
        if (representationCase_ == 5) {
          representationCase_ = 0;
          representation_ = null;
        }
        seriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public com.bentoml.grpc.v1.Series.Builder getSeriesBuilder() {
      return getSeriesFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.SeriesOrBuilder getSeriesOrBuilder() {
      if ((representationCase_ == 5) && (seriesBuilder_ != null)) {
        return seriesBuilder_.getMessageOrBuilder();
      } else {
        if (representationCase_ == 5) {
          return (com.bentoml.grpc.v1.Series) representation_;
        }
        return com.bentoml.grpc.v1.Series.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder> 
        getSeriesFieldBuilder() {
      if (seriesBuilder_ == null) {
        if (!(representationCase_ == 5)) {
          representation_ = com.bentoml.grpc.v1.Series.getDefaultInstance();
        }
        seriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder>(
                (com.bentoml.grpc.v1.Series) representation_,
                getParentForChildren(),
                isClean());
        representation_ = null;
      }
      representationCase_ = 5;
      onChanged();
      return seriesBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.File, com.bentoml.grpc.v1.File.Builder, com.bentoml.grpc.v1.FileOrBuilder> fileBuilder_;
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return representationCase_ == 6;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     * @return The file.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.File getFile() {
      if (fileBuilder_ == null) {
        if (representationCase_ == 6) {
          return (com.bentoml.grpc.v1.File) representation_;
        }
        return com.bentoml.grpc.v1.File.getDefaultInstance();
      } else {
        if (representationCase_ == 6) {
          return fileBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.File.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder setFile(com.bentoml.grpc.v1.File value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        representation_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      representationCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder setFile(
        com.bentoml.grpc.v1.File.Builder builderForValue) {
      if (fileBuilder_ == null) {
        representation_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      representationCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder mergeFile(com.bentoml.grpc.v1.File value) {
      if (fileBuilder_ == null) {
        if (representationCase_ == 6 &&
            representation_ != com.bentoml.grpc.v1.File.getDefaultInstance()) {
          representation_ = com.bentoml.grpc.v1.File.newBuilder((com.bentoml.grpc.v1.File) representation_)
              .mergeFrom(value).buildPartial();
        } else {
          representation_ = value;
        }
        onChanged();
      } else {
        if (representationCase_ == 6) {
          fileBuilder_.mergeFrom(value);
        } else {
          fileBuilder_.setMessage(value);
        }
      }
      representationCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        if (representationCase_ == 6) {
          representationCase_ = 0;
          representation_ = null;
          onChanged();
        }
      } else {
        if (representationCase_ == 6) {
          representationCase_ = 0;
          representation_ = null;
        }
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public com.bentoml.grpc.v1.File.Builder getFileBuilder() {
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.FileOrBuilder getFileOrBuilder() {
      if ((representationCase_ == 6) && (fileBuilder_ != null)) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        if (representationCase_ == 6) {
          return (com.bentoml.grpc.v1.File) representation_;
        }
        return com.bentoml.grpc.v1.File.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.File, com.bentoml.grpc.v1.File.Builder, com.bentoml.grpc.v1.FileOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        if (!(representationCase_ == 6)) {
          representation_ = com.bentoml.grpc.v1.File.getDefaultInstance();
        }
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.File, com.bentoml.grpc.v1.File.Builder, com.bentoml.grpc.v1.FileOrBuilder>(
                (com.bentoml.grpc.v1.File) representation_,
                getParentForChildren(),
                isClean());
        representation_ = null;
      }
      representationCase_ = 6;
      onChanged();
      return fileBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> textBuilder_;
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return representationCase_ == 7;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     * @return The text.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getText() {
      if (textBuilder_ == null) {
        if (representationCase_ == 7) {
          return (com.google.protobuf.StringValue) representation_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      } else {
        if (representationCase_ == 7) {
          return textBuilder_.getMessage();
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder setText(com.google.protobuf.StringValue value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        representation_ = value;
        onChanged();
      } else {
        textBuilder_.setMessage(value);
      }
      representationCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder setText(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (textBuilder_ == null) {
        representation_ = builderForValue.build();
        onChanged();
      } else {
        textBuilder_.setMessage(builderForValue.build());
      }
      representationCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder mergeText(com.google.protobuf.StringValue value) {
      if (textBuilder_ == null) {
        if (representationCase_ == 7 &&
            representation_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          representation_ = com.google.protobuf.StringValue.newBuilder((com.google.protobuf.StringValue) representation_)
              .mergeFrom(value).buildPartial();
        } else {
          representation_ = value;
        }
        onChanged();
      } else {
        if (representationCase_ == 7) {
          textBuilder_.mergeFrom(value);
        } else {
          textBuilder_.setMessage(value);
        }
      }
      representationCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder clearText() {
      if (textBuilder_ == null) {
        if (representationCase_ == 7) {
          representationCase_ = 0;
          representation_ = null;
          onChanged();
        }
      } else {
        if (representationCase_ == 7) {
          representationCase_ = 0;
          representation_ = null;
        }
        textBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public com.google.protobuf.StringValue.Builder getTextBuilder() {
      return getTextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getTextOrBuilder() {
      if ((representationCase_ == 7) && (textBuilder_ != null)) {
        return textBuilder_.getMessageOrBuilder();
      } else {
        if (representationCase_ == 7) {
          return (com.google.protobuf.StringValue) representation_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getTextFieldBuilder() {
      if (textBuilder_ == null) {
        if (!(representationCase_ == 7)) {
          representation_ = com.google.protobuf.StringValue.getDefaultInstance();
        }
        textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                (com.google.protobuf.StringValue) representation_,
                getParentForChildren(),
                isClean());
        representation_ = null;
      }
      representationCase_ = 7;
      onChanged();
      return textBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> jsonBuilder_;
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     * @return Whether the json field is set.
     */
    @java.lang.Override
    public boolean hasJson() {
      return representationCase_ == 8;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     * @return The json.
     */
    @java.lang.Override
    public com.google.protobuf.Value getJson() {
      if (jsonBuilder_ == null) {
        if (representationCase_ == 8) {
          return (com.google.protobuf.Value) representation_;
        }
        return com.google.protobuf.Value.getDefaultInstance();
      } else {
        if (representationCase_ == 8) {
          return jsonBuilder_.getMessage();
        }
        return com.google.protobuf.Value.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder setJson(com.google.protobuf.Value value) {
      if (jsonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        representation_ = value;
        onChanged();
      } else {
        jsonBuilder_.setMessage(value);
      }
      representationCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder setJson(
        com.google.protobuf.Value.Builder builderForValue) {
      if (jsonBuilder_ == null) {
        representation_ = builderForValue.build();
        onChanged();
      } else {
        jsonBuilder_.setMessage(builderForValue.build());
      }
      representationCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder mergeJson(com.google.protobuf.Value value) {
      if (jsonBuilder_ == null) {
        if (representationCase_ == 8 &&
            representation_ != com.google.protobuf.Value.getDefaultInstance()) {
          representation_ = com.google.protobuf.Value.newBuilder((com.google.protobuf.Value) representation_)
              .mergeFrom(value).buildPartial();
        } else {
          representation_ = value;
        }
        onChanged();
      } else {
        if (representationCase_ == 8) {
          jsonBuilder_.mergeFrom(value);
        } else {
          jsonBuilder_.setMessage(value);
        }
      }
      representationCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder clearJson() {
      if (jsonBuilder_ == null) {
        if (representationCase_ == 8) {
          representationCase_ = 0;
          representation_ = null;
          onChanged();
        }
      } else {
        if (representationCase_ == 8) {
          representationCase_ = 0;
          representation_ = null;
        }
        jsonBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public com.google.protobuf.Value.Builder getJsonBuilder() {
      return getJsonFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ValueOrBuilder getJsonOrBuilder() {
      if ((representationCase_ == 8) && (jsonBuilder_ != null)) {
        return jsonBuilder_.getMessageOrBuilder();
      } else {
        if (representationCase_ == 8) {
          return (com.google.protobuf.Value) representation_;
        }
        return com.google.protobuf.Value.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> 
        getJsonFieldBuilder() {
      if (jsonBuilder_ == null) {
        if (!(representationCase_ == 8)) {
          representation_ = com.google.protobuf.Value.getDefaultInstance();
        }
        jsonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                (com.google.protobuf.Value) representation_,
                getParentForChildren(),
                isClean());
        representation_ = null;
      }
      representationCase_ = 8;
      onChanged();
      return jsonBuilder_;
    }

    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 4;</code>
     * @return Whether the serializedBytes field is set.
     */
    public boolean hasSerializedBytes() {
      return representationCase_ == 4;
    }
    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 4;</code>
     * @return The serializedBytes.
     */
    public com.google.protobuf.ByteString getSerializedBytes() {
      if (representationCase_ == 4) {
        return (com.google.protobuf.ByteString) representation_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 4;</code>
     * @param value The serializedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setSerializedBytes(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      representationCase_ = 4;
      representation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerializedBytes() {
      if (representationCase_ == 4) {
        representationCase_ = 0;
        representation_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bentoml.grpc.v1.Part)
  }

  // @@protoc_insertion_point(class_scope:bentoml.grpc.v1.Part)
  private static final com.bentoml.grpc.v1.Part DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bentoml.grpc.v1.Part();
  }

  public static com.bentoml.grpc.v1.Part getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Part>
      PARSER = new com.google.protobuf.AbstractParser<Part>() {
    @java.lang.Override
    public Part parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Part> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Part> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bentoml.grpc.v1.Part getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

