// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public interface PartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bentoml.grpc.v1.Part)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   * @return Whether the ndarray field is set.
   */
  boolean hasNdarray();
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   * @return The ndarray.
   */
  com.bentoml.grpc.v1.NDArray getNdarray();
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   */
  com.bentoml.grpc.v1.NDArrayOrBuilder getNdarrayOrBuilder();

  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   * @return Whether the dataframe field is set.
   */
  boolean hasDataframe();
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   * @return The dataframe.
   */
  com.bentoml.grpc.v1.DataFrame getDataframe();
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   */
  com.bentoml.grpc.v1.DataFrameOrBuilder getDataframeOrBuilder();

  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   * @return Whether the series field is set.
   */
  boolean hasSeries();
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   * @return The series.
   */
  com.bentoml.grpc.v1.Series getSeries();
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   */
  com.bentoml.grpc.v1.SeriesOrBuilder getSeriesOrBuilder();

  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   * @return The file.
   */
  com.bentoml.grpc.v1.File getFile();
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   */
  com.bentoml.grpc.v1.FileOrBuilder getFileOrBuilder();

  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   * @return The text.
   */
  com.google.protobuf.StringValue getText();
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTextOrBuilder();

  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   * @return Whether the json field is set.
   */
  boolean hasJson();
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   * @return The json.
   */
  com.google.protobuf.Value getJson();
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   */
  com.google.protobuf.ValueOrBuilder getJsonOrBuilder();

  /**
   * <pre>
   * serialized_bytes is for data serialized in BentoML's internal serialization format.
   * </pre>
   *
   * <code>bytes serialized_bytes = 4;</code>
   * @return Whether the serializedBytes field is set.
   */
  boolean hasSerializedBytes();
  /**
   * <pre>
   * serialized_bytes is for data serialized in BentoML's internal serialization format.
   * </pre>
   *
   * <code>bytes serialized_bytes = 4;</code>
   * @return The serializedBytes.
   */
  com.google.protobuf.ByteString getSerializedBytes();

  com.bentoml.grpc.v1.Part.RepresentationCase getRepresentationCase();
}
