// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

/**
 * <pre>
 * Request message for incoming Call.
 * </pre>
 *
 * Protobuf type {@code bentoml.grpc.v1.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bentoml.grpc.v1.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bentoml.grpc.v1.Response.class, com.bentoml.grpc.v1.Response.Builder.class);
  }

  private int contentCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object content_;
  public enum ContentCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NDARRAY(1),
    DATAFRAME(3),
    SERIES(5),
    FILE(6),
    TEXT(7),
    JSON(8),
    MULTIPART(9),
    SERIALIZED_BYTES(2),
    CONTENT_NOT_SET(0);
    private final int value;
    private ContentCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentCase valueOf(int value) {
      return forNumber(value);
    }

    public static ContentCase forNumber(int value) {
      switch (value) {
        case 1: return NDARRAY;
        case 3: return DATAFRAME;
        case 5: return SERIES;
        case 6: return FILE;
        case 7: return TEXT;
        case 8: return JSON;
        case 9: return MULTIPART;
        case 2: return SERIALIZED_BYTES;
        case 0: return CONTENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ContentCase
  getContentCase() {
    return ContentCase.forNumber(
        contentCase_);
  }

  public static final int NDARRAY_FIELD_NUMBER = 1;
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   * @return Whether the ndarray field is set.
   */
  @java.lang.Override
  public boolean hasNdarray() {
    return contentCase_ == 1;
  }
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   * @return The ndarray.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.NDArray getNdarray() {
    if (contentCase_ == 1) {
       return (com.bentoml.grpc.v1.NDArray) content_;
    }
    return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
  }
  /**
   * <pre>
   * NDArray represents a n-dimensional array of arbitrary type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.NDArrayOrBuilder getNdarrayOrBuilder() {
    if (contentCase_ == 1) {
       return (com.bentoml.grpc.v1.NDArray) content_;
    }
    return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
  }

  public static final int DATAFRAME_FIELD_NUMBER = 3;
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   * @return Whether the dataframe field is set.
   */
  @java.lang.Override
  public boolean hasDataframe() {
    return contentCase_ == 3;
  }
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   * @return The dataframe.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.DataFrame getDataframe() {
    if (contentCase_ == 3) {
       return (com.bentoml.grpc.v1.DataFrame) content_;
    }
    return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
  }
  /**
   * <pre>
   * DataFrame represents any tabular data type. We are using
   * DataFrame as a trivial representation for tabular type.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.DataFrameOrBuilder getDataframeOrBuilder() {
    if (contentCase_ == 3) {
       return (com.bentoml.grpc.v1.DataFrame) content_;
    }
    return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
  }

  public static final int SERIES_FIELD_NUMBER = 5;
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   * @return Whether the series field is set.
   */
  @java.lang.Override
  public boolean hasSeries() {
    return contentCase_ == 5;
  }
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   * @return The series.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.Series getSeries() {
    if (contentCase_ == 5) {
       return (com.bentoml.grpc.v1.Series) content_;
    }
    return com.bentoml.grpc.v1.Series.getDefaultInstance();
  }
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Series series = 5;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.SeriesOrBuilder getSeriesOrBuilder() {
    if (contentCase_ == 5) {
       return (com.bentoml.grpc.v1.Series) content_;
    }
    return com.bentoml.grpc.v1.Series.getDefaultInstance();
  }

  public static final int FILE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return contentCase_ == 6;
  }
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   * @return The file.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.File getFile() {
    if (contentCase_ == 6) {
       return (com.bentoml.grpc.v1.File) content_;
    }
    return com.bentoml.grpc.v1.File.getDefaultInstance();
  }
  /**
   * <pre>
   * File represents for any arbitrary file type. This can be
   * plaintext, image, video, audio, etc.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.File file = 6;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.FileOrBuilder getFileOrBuilder() {
    if (contentCase_ == 6) {
       return (com.bentoml.grpc.v1.File) content_;
    }
    return com.bentoml.grpc.v1.File.getDefaultInstance();
  }

  public static final int TEXT_FIELD_NUMBER = 7;
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   * @return Whether the text field is set.
   */
  @java.lang.Override
  public boolean hasText() {
    return contentCase_ == 7;
  }
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   * @return The text.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getText() {
    if (contentCase_ == 7) {
       return (com.google.protobuf.StringValue) content_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }
  /**
   * <pre>
   * Text represents a string inputs.
   * </pre>
   *
   * <code>.google.protobuf.StringValue text = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getTextOrBuilder() {
    if (contentCase_ == 7) {
       return (com.google.protobuf.StringValue) content_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }

  public static final int JSON_FIELD_NUMBER = 8;
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   * @return Whether the json field is set.
   */
  @java.lang.Override
  public boolean hasJson() {
    return contentCase_ == 8;
  }
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   * @return The json.
   */
  @java.lang.Override
  public com.google.protobuf.Value getJson() {
    if (contentCase_ == 8) {
       return (com.google.protobuf.Value) content_;
    }
    return com.google.protobuf.Value.getDefaultInstance();
  }
  /**
   * <pre>
   * JSON is represented by using google.protobuf.Value.
   * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
   * </pre>
   *
   * <code>.google.protobuf.Value json = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ValueOrBuilder getJsonOrBuilder() {
    if (contentCase_ == 8) {
       return (com.google.protobuf.Value) content_;
    }
    return com.google.protobuf.Value.getDefaultInstance();
  }

  public static final int MULTIPART_FIELD_NUMBER = 9;
  /**
   * <pre>
   * Multipart represents a multipart message.
   * It comprises of a mapping from given type name to a subset of aforementioned types.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
   * @return Whether the multipart field is set.
   */
  @java.lang.Override
  public boolean hasMultipart() {
    return contentCase_ == 9;
  }
  /**
   * <pre>
   * Multipart represents a multipart message.
   * It comprises of a mapping from given type name to a subset of aforementioned types.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
   * @return The multipart.
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.Multipart getMultipart() {
    if (contentCase_ == 9) {
       return (com.bentoml.grpc.v1.Multipart) content_;
    }
    return com.bentoml.grpc.v1.Multipart.getDefaultInstance();
  }
  /**
   * <pre>
   * Multipart represents a multipart message.
   * It comprises of a mapping from given type name to a subset of aforementioned types.
   * </pre>
   *
   * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
   */
  @java.lang.Override
  public com.bentoml.grpc.v1.MultipartOrBuilder getMultipartOrBuilder() {
    if (contentCase_ == 9) {
       return (com.bentoml.grpc.v1.Multipart) content_;
    }
    return com.bentoml.grpc.v1.Multipart.getDefaultInstance();
  }

  public static final int SERIALIZED_BYTES_FIELD_NUMBER = 2;
  /**
   * <pre>
   * serialized_bytes is for data serialized in BentoML's internal serialization format.
   * </pre>
   *
   * <code>bytes serialized_bytes = 2;</code>
   * @return Whether the serializedBytes field is set.
   */
  @java.lang.Override
  public boolean hasSerializedBytes() {
    return contentCase_ == 2;
  }
  /**
   * <pre>
   * serialized_bytes is for data serialized in BentoML's internal serialization format.
   * </pre>
   *
   * <code>bytes serialized_bytes = 2;</code>
   * @return The serializedBytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSerializedBytes() {
    if (contentCase_ == 2) {
      return (com.google.protobuf.ByteString) content_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (contentCase_ == 1) {
      output.writeMessage(1, (com.bentoml.grpc.v1.NDArray) content_);
    }
    if (contentCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) content_);
    }
    if (contentCase_ == 3) {
      output.writeMessage(3, (com.bentoml.grpc.v1.DataFrame) content_);
    }
    if (contentCase_ == 5) {
      output.writeMessage(5, (com.bentoml.grpc.v1.Series) content_);
    }
    if (contentCase_ == 6) {
      output.writeMessage(6, (com.bentoml.grpc.v1.File) content_);
    }
    if (contentCase_ == 7) {
      output.writeMessage(7, (com.google.protobuf.StringValue) content_);
    }
    if (contentCase_ == 8) {
      output.writeMessage(8, (com.google.protobuf.Value) content_);
    }
    if (contentCase_ == 9) {
      output.writeMessage(9, (com.bentoml.grpc.v1.Multipart) content_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (contentCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.bentoml.grpc.v1.NDArray) content_);
    }
    if (contentCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) content_);
    }
    if (contentCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.bentoml.grpc.v1.DataFrame) content_);
    }
    if (contentCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.bentoml.grpc.v1.Series) content_);
    }
    if (contentCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.bentoml.grpc.v1.File) content_);
    }
    if (contentCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.google.protobuf.StringValue) content_);
    }
    if (contentCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.google.protobuf.Value) content_);
    }
    if (contentCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (com.bentoml.grpc.v1.Multipart) content_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bentoml.grpc.v1.Response)) {
      return super.equals(obj);
    }
    com.bentoml.grpc.v1.Response other = (com.bentoml.grpc.v1.Response) obj;

    if (!getContentCase().equals(other.getContentCase())) return false;
    switch (contentCase_) {
      case 1:
        if (!getNdarray()
            .equals(other.getNdarray())) return false;
        break;
      case 3:
        if (!getDataframe()
            .equals(other.getDataframe())) return false;
        break;
      case 5:
        if (!getSeries()
            .equals(other.getSeries())) return false;
        break;
      case 6:
        if (!getFile()
            .equals(other.getFile())) return false;
        break;
      case 7:
        if (!getText()
            .equals(other.getText())) return false;
        break;
      case 8:
        if (!getJson()
            .equals(other.getJson())) return false;
        break;
      case 9:
        if (!getMultipart()
            .equals(other.getMultipart())) return false;
        break;
      case 2:
        if (!getSerializedBytes()
            .equals(other.getSerializedBytes())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (contentCase_) {
      case 1:
        hash = (37 * hash) + NDARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getNdarray().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DATAFRAME_FIELD_NUMBER;
        hash = (53 * hash) + getDataframe().hashCode();
        break;
      case 5:
        hash = (37 * hash) + SERIES_FIELD_NUMBER;
        hash = (53 * hash) + getSeries().hashCode();
        break;
      case 6:
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
        break;
      case 7:
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        break;
      case 8:
        hash = (37 * hash) + JSON_FIELD_NUMBER;
        hash = (53 * hash) + getJson().hashCode();
        break;
      case 9:
        hash = (37 * hash) + MULTIPART_FIELD_NUMBER;
        hash = (53 * hash) + getMultipart().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SERIALIZED_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getSerializedBytes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bentoml.grpc.v1.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bentoml.grpc.v1.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bentoml.grpc.v1.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bentoml.grpc.v1.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for incoming Call.
   * </pre>
   *
   * Protobuf type {@code bentoml.grpc.v1.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bentoml.grpc.v1.Response)
      com.bentoml.grpc.v1.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bentoml.grpc.v1.Response.class, com.bentoml.grpc.v1.Response.Builder.class);
    }

    // Construct using com.bentoml.grpc.v1.Response.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (ndarrayBuilder_ != null) {
        ndarrayBuilder_.clear();
      }
      if (dataframeBuilder_ != null) {
        dataframeBuilder_.clear();
      }
      if (seriesBuilder_ != null) {
        seriesBuilder_.clear();
      }
      if (fileBuilder_ != null) {
        fileBuilder_.clear();
      }
      if (textBuilder_ != null) {
        textBuilder_.clear();
      }
      if (jsonBuilder_ != null) {
        jsonBuilder_.clear();
      }
      if (multipartBuilder_ != null) {
        multipartBuilder_.clear();
      }
      contentCase_ = 0;
      content_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Response_descriptor;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Response getDefaultInstanceForType() {
      return com.bentoml.grpc.v1.Response.getDefaultInstance();
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Response build() {
      com.bentoml.grpc.v1.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Response buildPartial() {
      com.bentoml.grpc.v1.Response result = new com.bentoml.grpc.v1.Response(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bentoml.grpc.v1.Response result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.bentoml.grpc.v1.Response result) {
      result.contentCase_ = contentCase_;
      result.content_ = this.content_;
      if (contentCase_ == 1 &&
          ndarrayBuilder_ != null) {
        result.content_ = ndarrayBuilder_.build();
      }
      if (contentCase_ == 3 &&
          dataframeBuilder_ != null) {
        result.content_ = dataframeBuilder_.build();
      }
      if (contentCase_ == 5 &&
          seriesBuilder_ != null) {
        result.content_ = seriesBuilder_.build();
      }
      if (contentCase_ == 6 &&
          fileBuilder_ != null) {
        result.content_ = fileBuilder_.build();
      }
      if (contentCase_ == 7 &&
          textBuilder_ != null) {
        result.content_ = textBuilder_.build();
      }
      if (contentCase_ == 8 &&
          jsonBuilder_ != null) {
        result.content_ = jsonBuilder_.build();
      }
      if (contentCase_ == 9 &&
          multipartBuilder_ != null) {
        result.content_ = multipartBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bentoml.grpc.v1.Response) {
        return mergeFrom((com.bentoml.grpc.v1.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bentoml.grpc.v1.Response other) {
      if (other == com.bentoml.grpc.v1.Response.getDefaultInstance()) return this;
      switch (other.getContentCase()) {
        case NDARRAY: {
          mergeNdarray(other.getNdarray());
          break;
        }
        case DATAFRAME: {
          mergeDataframe(other.getDataframe());
          break;
        }
        case SERIES: {
          mergeSeries(other.getSeries());
          break;
        }
        case FILE: {
          mergeFile(other.getFile());
          break;
        }
        case TEXT: {
          mergeText(other.getText());
          break;
        }
        case JSON: {
          mergeJson(other.getJson());
          break;
        }
        case MULTIPART: {
          mergeMultipart(other.getMultipart());
          break;
        }
        case SERIALIZED_BYTES: {
          setSerializedBytes(other.getSerializedBytes());
          break;
        }
        case CONTENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getNdarrayFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 1;
              break;
            } // case 10
            case 18: {
              content_ = input.readBytes();
              contentCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDataframeFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 3;
              break;
            } // case 26
            case 42: {
              input.readMessage(
                  getSeriesFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getFileFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getJsonFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 8;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getMultipartFieldBuilder().getBuilder(),
                  extensionRegistry);
              contentCase_ = 9;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int contentCase_ = 0;
    private java.lang.Object content_;
    public ContentCase
        getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public Builder clearContent() {
      contentCase_ = 0;
      content_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.NDArray, com.bentoml.grpc.v1.NDArray.Builder, com.bentoml.grpc.v1.NDArrayOrBuilder> ndarrayBuilder_;
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     * @return Whether the ndarray field is set.
     */
    @java.lang.Override
    public boolean hasNdarray() {
      return contentCase_ == 1;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     * @return The ndarray.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.NDArray getNdarray() {
      if (ndarrayBuilder_ == null) {
        if (contentCase_ == 1) {
          return (com.bentoml.grpc.v1.NDArray) content_;
        }
        return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
      } else {
        if (contentCase_ == 1) {
          return ndarrayBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder setNdarray(com.bentoml.grpc.v1.NDArray value) {
      if (ndarrayBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        ndarrayBuilder_.setMessage(value);
      }
      contentCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder setNdarray(
        com.bentoml.grpc.v1.NDArray.Builder builderForValue) {
      if (ndarrayBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        ndarrayBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder mergeNdarray(com.bentoml.grpc.v1.NDArray value) {
      if (ndarrayBuilder_ == null) {
        if (contentCase_ == 1 &&
            content_ != com.bentoml.grpc.v1.NDArray.getDefaultInstance()) {
          content_ = com.bentoml.grpc.v1.NDArray.newBuilder((com.bentoml.grpc.v1.NDArray) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 1) {
          ndarrayBuilder_.mergeFrom(value);
        } else {
          ndarrayBuilder_.setMessage(value);
        }
      }
      contentCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public Builder clearNdarray() {
      if (ndarrayBuilder_ == null) {
        if (contentCase_ == 1) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 1) {
          contentCase_ = 0;
          content_ = null;
        }
        ndarrayBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    public com.bentoml.grpc.v1.NDArray.Builder getNdarrayBuilder() {
      return getNdarrayFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.NDArrayOrBuilder getNdarrayOrBuilder() {
      if ((contentCase_ == 1) && (ndarrayBuilder_ != null)) {
        return ndarrayBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 1) {
          return (com.bentoml.grpc.v1.NDArray) content_;
        }
        return com.bentoml.grpc.v1.NDArray.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NDArray represents a n-dimensional array of arbitrary type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.NDArray ndarray = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.NDArray, com.bentoml.grpc.v1.NDArray.Builder, com.bentoml.grpc.v1.NDArrayOrBuilder> 
        getNdarrayFieldBuilder() {
      if (ndarrayBuilder_ == null) {
        if (!(contentCase_ == 1)) {
          content_ = com.bentoml.grpc.v1.NDArray.getDefaultInstance();
        }
        ndarrayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.NDArray, com.bentoml.grpc.v1.NDArray.Builder, com.bentoml.grpc.v1.NDArrayOrBuilder>(
                (com.bentoml.grpc.v1.NDArray) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 1;
      onChanged();
      return ndarrayBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.DataFrame, com.bentoml.grpc.v1.DataFrame.Builder, com.bentoml.grpc.v1.DataFrameOrBuilder> dataframeBuilder_;
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     * @return Whether the dataframe field is set.
     */
    @java.lang.Override
    public boolean hasDataframe() {
      return contentCase_ == 3;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     * @return The dataframe.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.DataFrame getDataframe() {
      if (dataframeBuilder_ == null) {
        if (contentCase_ == 3) {
          return (com.bentoml.grpc.v1.DataFrame) content_;
        }
        return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
      } else {
        if (contentCase_ == 3) {
          return dataframeBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder setDataframe(com.bentoml.grpc.v1.DataFrame value) {
      if (dataframeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        dataframeBuilder_.setMessage(value);
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder setDataframe(
        com.bentoml.grpc.v1.DataFrame.Builder builderForValue) {
      if (dataframeBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        dataframeBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder mergeDataframe(com.bentoml.grpc.v1.DataFrame value) {
      if (dataframeBuilder_ == null) {
        if (contentCase_ == 3 &&
            content_ != com.bentoml.grpc.v1.DataFrame.getDefaultInstance()) {
          content_ = com.bentoml.grpc.v1.DataFrame.newBuilder((com.bentoml.grpc.v1.DataFrame) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 3) {
          dataframeBuilder_.mergeFrom(value);
        } else {
          dataframeBuilder_.setMessage(value);
        }
      }
      contentCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public Builder clearDataframe() {
      if (dataframeBuilder_ == null) {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 3) {
          contentCase_ = 0;
          content_ = null;
        }
        dataframeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    public com.bentoml.grpc.v1.DataFrame.Builder getDataframeBuilder() {
      return getDataframeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.DataFrameOrBuilder getDataframeOrBuilder() {
      if ((contentCase_ == 3) && (dataframeBuilder_ != null)) {
        return dataframeBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 3) {
          return (com.bentoml.grpc.v1.DataFrame) content_;
        }
        return com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * DataFrame represents any tabular data type. We are using
     * DataFrame as a trivial representation for tabular type.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.DataFrame dataframe = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.DataFrame, com.bentoml.grpc.v1.DataFrame.Builder, com.bentoml.grpc.v1.DataFrameOrBuilder> 
        getDataframeFieldBuilder() {
      if (dataframeBuilder_ == null) {
        if (!(contentCase_ == 3)) {
          content_ = com.bentoml.grpc.v1.DataFrame.getDefaultInstance();
        }
        dataframeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.DataFrame, com.bentoml.grpc.v1.DataFrame.Builder, com.bentoml.grpc.v1.DataFrameOrBuilder>(
                (com.bentoml.grpc.v1.DataFrame) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 3;
      onChanged();
      return dataframeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder> seriesBuilder_;
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     * @return Whether the series field is set.
     */
    @java.lang.Override
    public boolean hasSeries() {
      return contentCase_ == 5;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     * @return The series.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.Series getSeries() {
      if (seriesBuilder_ == null) {
        if (contentCase_ == 5) {
          return (com.bentoml.grpc.v1.Series) content_;
        }
        return com.bentoml.grpc.v1.Series.getDefaultInstance();
      } else {
        if (contentCase_ == 5) {
          return seriesBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.Series.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder setSeries(com.bentoml.grpc.v1.Series value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        seriesBuilder_.setMessage(value);
      }
      contentCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder setSeries(
        com.bentoml.grpc.v1.Series.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        seriesBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder mergeSeries(com.bentoml.grpc.v1.Series value) {
      if (seriesBuilder_ == null) {
        if (contentCase_ == 5 &&
            content_ != com.bentoml.grpc.v1.Series.getDefaultInstance()) {
          content_ = com.bentoml.grpc.v1.Series.newBuilder((com.bentoml.grpc.v1.Series) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 5) {
          seriesBuilder_.mergeFrom(value);
        } else {
          seriesBuilder_.setMessage(value);
        }
      }
      contentCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public Builder clearSeries() {
      if (seriesBuilder_ == null) {
        if (contentCase_ == 5) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 5) {
          contentCase_ = 0;
          content_ = null;
        }
        seriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    public com.bentoml.grpc.v1.Series.Builder getSeriesBuilder() {
      return getSeriesFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.SeriesOrBuilder getSeriesOrBuilder() {
      if ((contentCase_ == 5) && (seriesBuilder_ != null)) {
        return seriesBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 5) {
          return (com.bentoml.grpc.v1.Series) content_;
        }
        return com.bentoml.grpc.v1.Series.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Series portrays a series of values. This can be used for
     * representing Series types in tabular data.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Series series = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder> 
        getSeriesFieldBuilder() {
      if (seriesBuilder_ == null) {
        if (!(contentCase_ == 5)) {
          content_ = com.bentoml.grpc.v1.Series.getDefaultInstance();
        }
        seriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.Series, com.bentoml.grpc.v1.Series.Builder, com.bentoml.grpc.v1.SeriesOrBuilder>(
                (com.bentoml.grpc.v1.Series) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 5;
      onChanged();
      return seriesBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.File, com.bentoml.grpc.v1.File.Builder, com.bentoml.grpc.v1.FileOrBuilder> fileBuilder_;
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return contentCase_ == 6;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     * @return The file.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.File getFile() {
      if (fileBuilder_ == null) {
        if (contentCase_ == 6) {
          return (com.bentoml.grpc.v1.File) content_;
        }
        return com.bentoml.grpc.v1.File.getDefaultInstance();
      } else {
        if (contentCase_ == 6) {
          return fileBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.File.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder setFile(com.bentoml.grpc.v1.File value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      contentCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder setFile(
        com.bentoml.grpc.v1.File.Builder builderForValue) {
      if (fileBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder mergeFile(com.bentoml.grpc.v1.File value) {
      if (fileBuilder_ == null) {
        if (contentCase_ == 6 &&
            content_ != com.bentoml.grpc.v1.File.getDefaultInstance()) {
          content_ = com.bentoml.grpc.v1.File.newBuilder((com.bentoml.grpc.v1.File) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 6) {
          fileBuilder_.mergeFrom(value);
        } else {
          fileBuilder_.setMessage(value);
        }
      }
      contentCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        if (contentCase_ == 6) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 6) {
          contentCase_ = 0;
          content_ = null;
        }
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    public com.bentoml.grpc.v1.File.Builder getFileBuilder() {
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.FileOrBuilder getFileOrBuilder() {
      if ((contentCase_ == 6) && (fileBuilder_ != null)) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 6) {
          return (com.bentoml.grpc.v1.File) content_;
        }
        return com.bentoml.grpc.v1.File.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * File represents for any arbitrary file type. This can be
     * plaintext, image, video, audio, etc.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.File file = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.File, com.bentoml.grpc.v1.File.Builder, com.bentoml.grpc.v1.FileOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        if (!(contentCase_ == 6)) {
          content_ = com.bentoml.grpc.v1.File.getDefaultInstance();
        }
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.File, com.bentoml.grpc.v1.File.Builder, com.bentoml.grpc.v1.FileOrBuilder>(
                (com.bentoml.grpc.v1.File) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 6;
      onChanged();
      return fileBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> textBuilder_;
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return contentCase_ == 7;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     * @return The text.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getText() {
      if (textBuilder_ == null) {
        if (contentCase_ == 7) {
          return (com.google.protobuf.StringValue) content_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      } else {
        if (contentCase_ == 7) {
          return textBuilder_.getMessage();
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder setText(com.google.protobuf.StringValue value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        textBuilder_.setMessage(value);
      }
      contentCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder setText(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (textBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        textBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder mergeText(com.google.protobuf.StringValue value) {
      if (textBuilder_ == null) {
        if (contentCase_ == 7 &&
            content_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          content_ = com.google.protobuf.StringValue.newBuilder((com.google.protobuf.StringValue) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 7) {
          textBuilder_.mergeFrom(value);
        } else {
          textBuilder_.setMessage(value);
        }
      }
      contentCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public Builder clearText() {
      if (textBuilder_ == null) {
        if (contentCase_ == 7) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 7) {
          contentCase_ = 0;
          content_ = null;
        }
        textBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    public com.google.protobuf.StringValue.Builder getTextBuilder() {
      return getTextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getTextOrBuilder() {
      if ((contentCase_ == 7) && (textBuilder_ != null)) {
        return textBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 7) {
          return (com.google.protobuf.StringValue) content_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Text represents a string inputs.
     * </pre>
     *
     * <code>.google.protobuf.StringValue text = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getTextFieldBuilder() {
      if (textBuilder_ == null) {
        if (!(contentCase_ == 7)) {
          content_ = com.google.protobuf.StringValue.getDefaultInstance();
        }
        textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                (com.google.protobuf.StringValue) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 7;
      onChanged();
      return textBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> jsonBuilder_;
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     * @return Whether the json field is set.
     */
    @java.lang.Override
    public boolean hasJson() {
      return contentCase_ == 8;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     * @return The json.
     */
    @java.lang.Override
    public com.google.protobuf.Value getJson() {
      if (jsonBuilder_ == null) {
        if (contentCase_ == 8) {
          return (com.google.protobuf.Value) content_;
        }
        return com.google.protobuf.Value.getDefaultInstance();
      } else {
        if (contentCase_ == 8) {
          return jsonBuilder_.getMessage();
        }
        return com.google.protobuf.Value.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder setJson(com.google.protobuf.Value value) {
      if (jsonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        jsonBuilder_.setMessage(value);
      }
      contentCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder setJson(
        com.google.protobuf.Value.Builder builderForValue) {
      if (jsonBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        jsonBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder mergeJson(com.google.protobuf.Value value) {
      if (jsonBuilder_ == null) {
        if (contentCase_ == 8 &&
            content_ != com.google.protobuf.Value.getDefaultInstance()) {
          content_ = com.google.protobuf.Value.newBuilder((com.google.protobuf.Value) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 8) {
          jsonBuilder_.mergeFrom(value);
        } else {
          jsonBuilder_.setMessage(value);
        }
      }
      contentCase_ = 8;
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public Builder clearJson() {
      if (jsonBuilder_ == null) {
        if (contentCase_ == 8) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 8) {
          contentCase_ = 0;
          content_ = null;
        }
        jsonBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    public com.google.protobuf.Value.Builder getJsonBuilder() {
      return getJsonFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ValueOrBuilder getJsonOrBuilder() {
      if ((contentCase_ == 8) && (jsonBuilder_ != null)) {
        return jsonBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 8) {
          return (com.google.protobuf.Value) content_;
        }
        return com.google.protobuf.Value.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * JSON is represented by using google.protobuf.Value.
     * see https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto
     * </pre>
     *
     * <code>.google.protobuf.Value json = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> 
        getJsonFieldBuilder() {
      if (jsonBuilder_ == null) {
        if (!(contentCase_ == 8)) {
          content_ = com.google.protobuf.Value.getDefaultInstance();
        }
        jsonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                (com.google.protobuf.Value) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 8;
      onChanged();
      return jsonBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.Multipart, com.bentoml.grpc.v1.Multipart.Builder, com.bentoml.grpc.v1.MultipartOrBuilder> multipartBuilder_;
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     * @return Whether the multipart field is set.
     */
    @java.lang.Override
    public boolean hasMultipart() {
      return contentCase_ == 9;
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     * @return The multipart.
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.Multipart getMultipart() {
      if (multipartBuilder_ == null) {
        if (contentCase_ == 9) {
          return (com.bentoml.grpc.v1.Multipart) content_;
        }
        return com.bentoml.grpc.v1.Multipart.getDefaultInstance();
      } else {
        if (contentCase_ == 9) {
          return multipartBuilder_.getMessage();
        }
        return com.bentoml.grpc.v1.Multipart.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     */
    public Builder setMultipart(com.bentoml.grpc.v1.Multipart value) {
      if (multipartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;
        onChanged();
      } else {
        multipartBuilder_.setMessage(value);
      }
      contentCase_ = 9;
      return this;
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     */
    public Builder setMultipart(
        com.bentoml.grpc.v1.Multipart.Builder builderForValue) {
      if (multipartBuilder_ == null) {
        content_ = builderForValue.build();
        onChanged();
      } else {
        multipartBuilder_.setMessage(builderForValue.build());
      }
      contentCase_ = 9;
      return this;
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     */
    public Builder mergeMultipart(com.bentoml.grpc.v1.Multipart value) {
      if (multipartBuilder_ == null) {
        if (contentCase_ == 9 &&
            content_ != com.bentoml.grpc.v1.Multipart.getDefaultInstance()) {
          content_ = com.bentoml.grpc.v1.Multipart.newBuilder((com.bentoml.grpc.v1.Multipart) content_)
              .mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }
        onChanged();
      } else {
        if (contentCase_ == 9) {
          multipartBuilder_.mergeFrom(value);
        } else {
          multipartBuilder_.setMessage(value);
        }
      }
      contentCase_ = 9;
      return this;
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     */
    public Builder clearMultipart() {
      if (multipartBuilder_ == null) {
        if (contentCase_ == 9) {
          contentCase_ = 0;
          content_ = null;
          onChanged();
        }
      } else {
        if (contentCase_ == 9) {
          contentCase_ = 0;
          content_ = null;
        }
        multipartBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     */
    public com.bentoml.grpc.v1.Multipart.Builder getMultipartBuilder() {
      return getMultipartFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     */
    @java.lang.Override
    public com.bentoml.grpc.v1.MultipartOrBuilder getMultipartOrBuilder() {
      if ((contentCase_ == 9) && (multipartBuilder_ != null)) {
        return multipartBuilder_.getMessageOrBuilder();
      } else {
        if (contentCase_ == 9) {
          return (com.bentoml.grpc.v1.Multipart) content_;
        }
        return com.bentoml.grpc.v1.Multipart.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Multipart represents a multipart message.
     * It comprises of a mapping from given type name to a subset of aforementioned types.
     * </pre>
     *
     * <code>.bentoml.grpc.v1.Multipart multipart = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bentoml.grpc.v1.Multipart, com.bentoml.grpc.v1.Multipart.Builder, com.bentoml.grpc.v1.MultipartOrBuilder> 
        getMultipartFieldBuilder() {
      if (multipartBuilder_ == null) {
        if (!(contentCase_ == 9)) {
          content_ = com.bentoml.grpc.v1.Multipart.getDefaultInstance();
        }
        multipartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bentoml.grpc.v1.Multipart, com.bentoml.grpc.v1.Multipart.Builder, com.bentoml.grpc.v1.MultipartOrBuilder>(
                (com.bentoml.grpc.v1.Multipart) content_,
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      contentCase_ = 9;
      onChanged();
      return multipartBuilder_;
    }

    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 2;</code>
     * @return Whether the serializedBytes field is set.
     */
    public boolean hasSerializedBytes() {
      return contentCase_ == 2;
    }
    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 2;</code>
     * @return The serializedBytes.
     */
    public com.google.protobuf.ByteString getSerializedBytes() {
      if (contentCase_ == 2) {
        return (com.google.protobuf.ByteString) content_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 2;</code>
     * @param value The serializedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setSerializedBytes(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      contentCase_ = 2;
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * serialized_bytes is for data serialized in BentoML's internal serialization format.
     * </pre>
     *
     * <code>bytes serialized_bytes = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerializedBytes() {
      if (contentCase_ == 2) {
        contentCase_ = 0;
        content_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bentoml.grpc.v1.Response)
  }

  // @@protoc_insertion_point(class_scope:bentoml.grpc.v1.Response)
  private static final com.bentoml.grpc.v1.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bentoml.grpc.v1.Response();
  }

  public static com.bentoml.grpc.v1.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bentoml.grpc.v1.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

