// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

/**
 * <pre>
 * Series portrays a series of values. This can be used for
 * representing Series types in tabular data.
 * </pre>
 *
 * Protobuf type {@code bentoml.grpc.v1.Series}
 */
public final class Series extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bentoml.grpc.v1.Series)
    SeriesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Series.newBuilder() to construct.
  private Series(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Series() {
    boolValues_ = emptyBooleanList();
    floatValues_ = emptyFloatList();
    int32Values_ = emptyIntList();
    int64Values_ = emptyLongList();
    stringValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    doubleValues_ = emptyDoubleList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Series();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Series_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Series_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bentoml.grpc.v1.Series.class, com.bentoml.grpc.v1.Series.Builder.class);
  }

  public static final int BOOL_VALUES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.BooleanList boolValues_ =
      emptyBooleanList();
  /**
   * <pre>
   * A bool parameter value
   * </pre>
   *
   * <code>repeated bool bool_values = 1 [packed = true];</code>
   * @return A list containing the boolValues.
   */
  @java.lang.Override
  public java.util.List<java.lang.Boolean>
      getBoolValuesList() {
    return boolValues_;
  }
  /**
   * <pre>
   * A bool parameter value
   * </pre>
   *
   * <code>repeated bool bool_values = 1 [packed = true];</code>
   * @return The count of boolValues.
   */
  public int getBoolValuesCount() {
    return boolValues_.size();
  }
  /**
   * <pre>
   * A bool parameter value
   * </pre>
   *
   * <code>repeated bool bool_values = 1 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The boolValues at the given index.
   */
  public boolean getBoolValues(int index) {
    return boolValues_.getBoolean(index);
  }
  private int boolValuesMemoizedSerializedSize = -1;

  public static final int FLOAT_VALUES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList floatValues_ =
      emptyFloatList();
  /**
   * <pre>
   * A float parameter value
   * </pre>
   *
   * <code>repeated float float_values = 2 [packed = true];</code>
   * @return A list containing the floatValues.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getFloatValuesList() {
    return floatValues_;
  }
  /**
   * <pre>
   * A float parameter value
   * </pre>
   *
   * <code>repeated float float_values = 2 [packed = true];</code>
   * @return The count of floatValues.
   */
  public int getFloatValuesCount() {
    return floatValues_.size();
  }
  /**
   * <pre>
   * A float parameter value
   * </pre>
   *
   * <code>repeated float float_values = 2 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The floatValues at the given index.
   */
  public float getFloatValues(int index) {
    return floatValues_.getFloat(index);
  }
  private int floatValuesMemoizedSerializedSize = -1;

  public static final int INT32_VALUES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList int32Values_ =
      emptyIntList();
  /**
   * <pre>
   * A int32 parameter value
   * </pre>
   *
   * <code>repeated int32 int32_values = 3 [packed = true];</code>
   * @return A list containing the int32Values.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getInt32ValuesList() {
    return int32Values_;
  }
  /**
   * <pre>
   * A int32 parameter value
   * </pre>
   *
   * <code>repeated int32 int32_values = 3 [packed = true];</code>
   * @return The count of int32Values.
   */
  public int getInt32ValuesCount() {
    return int32Values_.size();
  }
  /**
   * <pre>
   * A int32 parameter value
   * </pre>
   *
   * <code>repeated int32 int32_values = 3 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The int32Values at the given index.
   */
  public int getInt32Values(int index) {
    return int32Values_.getInt(index);
  }
  private int int32ValuesMemoizedSerializedSize = -1;

  public static final int INT64_VALUES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList int64Values_ =
      emptyLongList();
  /**
   * <pre>
   * A int64 parameter value
   * </pre>
   *
   * <code>repeated int64 int64_values = 6 [packed = true];</code>
   * @return A list containing the int64Values.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getInt64ValuesList() {
    return int64Values_;
  }
  /**
   * <pre>
   * A int64 parameter value
   * </pre>
   *
   * <code>repeated int64 int64_values = 6 [packed = true];</code>
   * @return The count of int64Values.
   */
  public int getInt64ValuesCount() {
    return int64Values_.size();
  }
  /**
   * <pre>
   * A int64 parameter value
   * </pre>
   *
   * <code>repeated int64 int64_values = 6 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The int64Values at the given index.
   */
  public long getInt64Values(int index) {
    return int64Values_.getLong(index);
  }
  private int int64ValuesMemoizedSerializedSize = -1;

  public static final int STRING_VALUES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList stringValues_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @return A list containing the stringValues.
   */
  public com.google.protobuf.ProtocolStringList
      getStringValuesList() {
    return stringValues_;
  }
  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @return The count of stringValues.
   */
  public int getStringValuesCount() {
    return stringValues_.size();
  }
  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @param index The index of the element to return.
   * @return The stringValues at the given index.
   */
  public java.lang.String getStringValues(int index) {
    return stringValues_.get(index);
  }
  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stringValues at the given index.
   */
  public com.google.protobuf.ByteString
      getStringValuesBytes(int index) {
    return stringValues_.getByteString(index);
  }

  public static final int DOUBLE_VALUES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList doubleValues_ =
      emptyDoubleList();
  /**
   * <pre>
   * represents a double parameter value.
   * </pre>
   *
   * <code>repeated double double_values = 4 [packed = true];</code>
   * @return A list containing the doubleValues.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getDoubleValuesList() {
    return doubleValues_;
  }
  /**
   * <pre>
   * represents a double parameter value.
   * </pre>
   *
   * <code>repeated double double_values = 4 [packed = true];</code>
   * @return The count of doubleValues.
   */
  public int getDoubleValuesCount() {
    return doubleValues_.size();
  }
  /**
   * <pre>
   * represents a double parameter value.
   * </pre>
   *
   * <code>repeated double double_values = 4 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The doubleValues at the given index.
   */
  public double getDoubleValues(int index) {
    return doubleValues_.getDouble(index);
  }
  private int doubleValuesMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getBoolValuesList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(boolValuesMemoizedSerializedSize);
    }
    for (int i = 0; i < boolValues_.size(); i++) {
      output.writeBoolNoTag(boolValues_.getBoolean(i));
    }
    if (getFloatValuesList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(floatValuesMemoizedSerializedSize);
    }
    for (int i = 0; i < floatValues_.size(); i++) {
      output.writeFloatNoTag(floatValues_.getFloat(i));
    }
    if (getInt32ValuesList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(int32ValuesMemoizedSerializedSize);
    }
    for (int i = 0; i < int32Values_.size(); i++) {
      output.writeInt32NoTag(int32Values_.getInt(i));
    }
    if (getDoubleValuesList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(doubleValuesMemoizedSerializedSize);
    }
    for (int i = 0; i < doubleValues_.size(); i++) {
      output.writeDoubleNoTag(doubleValues_.getDouble(i));
    }
    for (int i = 0; i < stringValues_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, stringValues_.getRaw(i));
    }
    if (getInt64ValuesList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(int64ValuesMemoizedSerializedSize);
    }
    for (int i = 0; i < int64Values_.size(); i++) {
      output.writeInt64NoTag(int64Values_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 1 * getBoolValuesList().size();
      size += dataSize;
      if (!getBoolValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      boolValuesMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 4 * getFloatValuesList().size();
      size += dataSize;
      if (!getFloatValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      floatValuesMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < int32Values_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(int32Values_.getInt(i));
      }
      size += dataSize;
      if (!getInt32ValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      int32ValuesMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 8 * getDoubleValuesList().size();
      size += dataSize;
      if (!getDoubleValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      doubleValuesMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stringValues_.size(); i++) {
        dataSize += computeStringSizeNoTag(stringValues_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStringValuesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < int64Values_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(int64Values_.getLong(i));
      }
      size += dataSize;
      if (!getInt64ValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      int64ValuesMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bentoml.grpc.v1.Series)) {
      return super.equals(obj);
    }
    com.bentoml.grpc.v1.Series other = (com.bentoml.grpc.v1.Series) obj;

    if (!getBoolValuesList()
        .equals(other.getBoolValuesList())) return false;
    if (!getFloatValuesList()
        .equals(other.getFloatValuesList())) return false;
    if (!getInt32ValuesList()
        .equals(other.getInt32ValuesList())) return false;
    if (!getInt64ValuesList()
        .equals(other.getInt64ValuesList())) return false;
    if (!getStringValuesList()
        .equals(other.getStringValuesList())) return false;
    if (!getDoubleValuesList()
        .equals(other.getDoubleValuesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBoolValuesCount() > 0) {
      hash = (37 * hash) + BOOL_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getBoolValuesList().hashCode();
    }
    if (getFloatValuesCount() > 0) {
      hash = (37 * hash) + FLOAT_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getFloatValuesList().hashCode();
    }
    if (getInt32ValuesCount() > 0) {
      hash = (37 * hash) + INT32_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getInt32ValuesList().hashCode();
    }
    if (getInt64ValuesCount() > 0) {
      hash = (37 * hash) + INT64_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getInt64ValuesList().hashCode();
    }
    if (getStringValuesCount() > 0) {
      hash = (37 * hash) + STRING_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getStringValuesList().hashCode();
    }
    if (getDoubleValuesCount() > 0) {
      hash = (37 * hash) + DOUBLE_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getDoubleValuesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bentoml.grpc.v1.Series parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bentoml.grpc.v1.Series parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bentoml.grpc.v1.Series parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bentoml.grpc.v1.Series parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bentoml.grpc.v1.Series prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Series portrays a series of values. This can be used for
   * representing Series types in tabular data.
   * </pre>
   *
   * Protobuf type {@code bentoml.grpc.v1.Series}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bentoml.grpc.v1.Series)
      com.bentoml.grpc.v1.SeriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Series_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Series_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bentoml.grpc.v1.Series.class, com.bentoml.grpc.v1.Series.Builder.class);
    }

    // Construct using com.bentoml.grpc.v1.Series.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      boolValues_ = emptyBooleanList();
      floatValues_ = emptyFloatList();
      int32Values_ = emptyIntList();
      int64Values_ = emptyLongList();
      stringValues_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      doubleValues_ = emptyDoubleList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bentoml.grpc.v1.ServiceProto.internal_static_bentoml_grpc_v1_Series_descriptor;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Series getDefaultInstanceForType() {
      return com.bentoml.grpc.v1.Series.getDefaultInstance();
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Series build() {
      com.bentoml.grpc.v1.Series result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bentoml.grpc.v1.Series buildPartial() {
      com.bentoml.grpc.v1.Series result = new com.bentoml.grpc.v1.Series(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bentoml.grpc.v1.Series result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        boolValues_.makeImmutable();
        result.boolValues_ = boolValues_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        floatValues_.makeImmutable();
        result.floatValues_ = floatValues_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        int32Values_.makeImmutable();
        result.int32Values_ = int32Values_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        int64Values_.makeImmutable();
        result.int64Values_ = int64Values_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        stringValues_.makeImmutable();
        result.stringValues_ = stringValues_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        doubleValues_.makeImmutable();
        result.doubleValues_ = doubleValues_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bentoml.grpc.v1.Series) {
        return mergeFrom((com.bentoml.grpc.v1.Series)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bentoml.grpc.v1.Series other) {
      if (other == com.bentoml.grpc.v1.Series.getDefaultInstance()) return this;
      if (!other.boolValues_.isEmpty()) {
        if (boolValues_.isEmpty()) {
          boolValues_ = other.boolValues_;
          boolValues_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureBoolValuesIsMutable();
          boolValues_.addAll(other.boolValues_);
        }
        onChanged();
      }
      if (!other.floatValues_.isEmpty()) {
        if (floatValues_.isEmpty()) {
          floatValues_ = other.floatValues_;
          floatValues_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureFloatValuesIsMutable();
          floatValues_.addAll(other.floatValues_);
        }
        onChanged();
      }
      if (!other.int32Values_.isEmpty()) {
        if (int32Values_.isEmpty()) {
          int32Values_ = other.int32Values_;
          int32Values_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureInt32ValuesIsMutable();
          int32Values_.addAll(other.int32Values_);
        }
        onChanged();
      }
      if (!other.int64Values_.isEmpty()) {
        if (int64Values_.isEmpty()) {
          int64Values_ = other.int64Values_;
          int64Values_.makeImmutable();
          bitField0_ |= 0x00000008;
        } else {
          ensureInt64ValuesIsMutable();
          int64Values_.addAll(other.int64Values_);
        }
        onChanged();
      }
      if (!other.stringValues_.isEmpty()) {
        if (stringValues_.isEmpty()) {
          stringValues_ = other.stringValues_;
          bitField0_ |= 0x00000010;
        } else {
          ensureStringValuesIsMutable();
          stringValues_.addAll(other.stringValues_);
        }
        onChanged();
      }
      if (!other.doubleValues_.isEmpty()) {
        if (doubleValues_.isEmpty()) {
          doubleValues_ = other.doubleValues_;
          doubleValues_.makeImmutable();
          bitField0_ |= 0x00000020;
        } else {
          ensureDoubleValuesIsMutable();
          doubleValues_.addAll(other.doubleValues_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              boolean v = input.readBool();
              ensureBoolValuesIsMutable();
              boolValues_.addBoolean(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureBoolValuesIsMutable(length / 1);
              while (input.getBytesUntilLimit() > 0) {
                boolValues_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 21: {
              float v = input.readFloat();
              ensureFloatValuesIsMutable();
              floatValues_.addFloat(v);
              break;
            } // case 21
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureFloatValuesIsMutable(length / 4);
              while (input.getBytesUntilLimit() > 0) {
                floatValues_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 24: {
              int v = input.readInt32();
              ensureInt32ValuesIsMutable();
              int32Values_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureInt32ValuesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                int32Values_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 33: {
              double v = input.readDouble();
              ensureDoubleValuesIsMutable();
              doubleValues_.addDouble(v);
              break;
            } // case 33
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureDoubleValuesIsMutable(length / 8);
              while (input.getBytesUntilLimit() > 0) {
                doubleValues_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureStringValuesIsMutable();
              stringValues_.add(s);
              break;
            } // case 42
            case 48: {
              long v = input.readInt64();
              ensureInt64ValuesIsMutable();
              int64Values_.addLong(v);
              break;
            } // case 48
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureInt64ValuesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                int64Values_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.BooleanList boolValues_ = emptyBooleanList();
    private void ensureBoolValuesIsMutable() {
      if (!boolValues_.isModifiable()) {
        boolValues_ = makeMutableCopy(boolValues_);
      }
      bitField0_ |= 0x00000001;
    }
    private void ensureBoolValuesIsMutable(int capacity) {
      if (!boolValues_.isModifiable()) {
        boolValues_ = makeMutableCopy(boolValues_, capacity);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * A bool parameter value
     * </pre>
     *
     * <code>repeated bool bool_values = 1 [packed = true];</code>
     * @return A list containing the boolValues.
     */
    public java.util.List<java.lang.Boolean>
        getBoolValuesList() {
      boolValues_.makeImmutable();
      return boolValues_;
    }
    /**
     * <pre>
     * A bool parameter value
     * </pre>
     *
     * <code>repeated bool bool_values = 1 [packed = true];</code>
     * @return The count of boolValues.
     */
    public int getBoolValuesCount() {
      return boolValues_.size();
    }
    /**
     * <pre>
     * A bool parameter value
     * </pre>
     *
     * <code>repeated bool bool_values = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The boolValues at the given index.
     */
    public boolean getBoolValues(int index) {
      return boolValues_.getBoolean(index);
    }
    /**
     * <pre>
     * A bool parameter value
     * </pre>
     *
     * <code>repeated bool bool_values = 1 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The boolValues to set.
     * @return This builder for chaining.
     */
    public Builder setBoolValues(
        int index, boolean value) {

      ensureBoolValuesIsMutable();
      boolValues_.setBoolean(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A bool parameter value
     * </pre>
     *
     * <code>repeated bool bool_values = 1 [packed = true];</code>
     * @param value The boolValues to add.
     * @return This builder for chaining.
     */
    public Builder addBoolValues(boolean value) {

      ensureBoolValuesIsMutable();
      boolValues_.addBoolean(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A bool parameter value
     * </pre>
     *
     * <code>repeated bool bool_values = 1 [packed = true];</code>
     * @param values The boolValues to add.
     * @return This builder for chaining.
     */
    public Builder addAllBoolValues(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureBoolValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, boolValues_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A bool parameter value
     * </pre>
     *
     * <code>repeated bool bool_values = 1 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolValues() {
      boolValues_ = emptyBooleanList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList floatValues_ = emptyFloatList();
    private void ensureFloatValuesIsMutable() {
      if (!floatValues_.isModifiable()) {
        floatValues_ = makeMutableCopy(floatValues_);
      }
      bitField0_ |= 0x00000002;
    }
    private void ensureFloatValuesIsMutable(int capacity) {
      if (!floatValues_.isModifiable()) {
        floatValues_ = makeMutableCopy(floatValues_, capacity);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * A float parameter value
     * </pre>
     *
     * <code>repeated float float_values = 2 [packed = true];</code>
     * @return A list containing the floatValues.
     */
    public java.util.List<java.lang.Float>
        getFloatValuesList() {
      floatValues_.makeImmutable();
      return floatValues_;
    }
    /**
     * <pre>
     * A float parameter value
     * </pre>
     *
     * <code>repeated float float_values = 2 [packed = true];</code>
     * @return The count of floatValues.
     */
    public int getFloatValuesCount() {
      return floatValues_.size();
    }
    /**
     * <pre>
     * A float parameter value
     * </pre>
     *
     * <code>repeated float float_values = 2 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The floatValues at the given index.
     */
    public float getFloatValues(int index) {
      return floatValues_.getFloat(index);
    }
    /**
     * <pre>
     * A float parameter value
     * </pre>
     *
     * <code>repeated float float_values = 2 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The floatValues to set.
     * @return This builder for chaining.
     */
    public Builder setFloatValues(
        int index, float value) {

      ensureFloatValuesIsMutable();
      floatValues_.setFloat(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A float parameter value
     * </pre>
     *
     * <code>repeated float float_values = 2 [packed = true];</code>
     * @param value The floatValues to add.
     * @return This builder for chaining.
     */
    public Builder addFloatValues(float value) {

      ensureFloatValuesIsMutable();
      floatValues_.addFloat(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A float parameter value
     * </pre>
     *
     * <code>repeated float float_values = 2 [packed = true];</code>
     * @param values The floatValues to add.
     * @return This builder for chaining.
     */
    public Builder addAllFloatValues(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureFloatValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, floatValues_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A float parameter value
     * </pre>
     *
     * <code>repeated float float_values = 2 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearFloatValues() {
      floatValues_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList int32Values_ = emptyIntList();
    private void ensureInt32ValuesIsMutable() {
      if (!int32Values_.isModifiable()) {
        int32Values_ = makeMutableCopy(int32Values_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * A int32 parameter value
     * </pre>
     *
     * <code>repeated int32 int32_values = 3 [packed = true];</code>
     * @return A list containing the int32Values.
     */
    public java.util.List<java.lang.Integer>
        getInt32ValuesList() {
      int32Values_.makeImmutable();
      return int32Values_;
    }
    /**
     * <pre>
     * A int32 parameter value
     * </pre>
     *
     * <code>repeated int32 int32_values = 3 [packed = true];</code>
     * @return The count of int32Values.
     */
    public int getInt32ValuesCount() {
      return int32Values_.size();
    }
    /**
     * <pre>
     * A int32 parameter value
     * </pre>
     *
     * <code>repeated int32 int32_values = 3 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The int32Values at the given index.
     */
    public int getInt32Values(int index) {
      return int32Values_.getInt(index);
    }
    /**
     * <pre>
     * A int32 parameter value
     * </pre>
     *
     * <code>repeated int32 int32_values = 3 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The int32Values to set.
     * @return This builder for chaining.
     */
    public Builder setInt32Values(
        int index, int value) {

      ensureInt32ValuesIsMutable();
      int32Values_.setInt(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A int32 parameter value
     * </pre>
     *
     * <code>repeated int32 int32_values = 3 [packed = true];</code>
     * @param value The int32Values to add.
     * @return This builder for chaining.
     */
    public Builder addInt32Values(int value) {

      ensureInt32ValuesIsMutable();
      int32Values_.addInt(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A int32 parameter value
     * </pre>
     *
     * <code>repeated int32 int32_values = 3 [packed = true];</code>
     * @param values The int32Values to add.
     * @return This builder for chaining.
     */
    public Builder addAllInt32Values(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureInt32ValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, int32Values_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A int32 parameter value
     * </pre>
     *
     * <code>repeated int32 int32_values = 3 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearInt32Values() {
      int32Values_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList int64Values_ = emptyLongList();
    private void ensureInt64ValuesIsMutable() {
      if (!int64Values_.isModifiable()) {
        int64Values_ = makeMutableCopy(int64Values_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * A int64 parameter value
     * </pre>
     *
     * <code>repeated int64 int64_values = 6 [packed = true];</code>
     * @return A list containing the int64Values.
     */
    public java.util.List<java.lang.Long>
        getInt64ValuesList() {
      int64Values_.makeImmutable();
      return int64Values_;
    }
    /**
     * <pre>
     * A int64 parameter value
     * </pre>
     *
     * <code>repeated int64 int64_values = 6 [packed = true];</code>
     * @return The count of int64Values.
     */
    public int getInt64ValuesCount() {
      return int64Values_.size();
    }
    /**
     * <pre>
     * A int64 parameter value
     * </pre>
     *
     * <code>repeated int64 int64_values = 6 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The int64Values at the given index.
     */
    public long getInt64Values(int index) {
      return int64Values_.getLong(index);
    }
    /**
     * <pre>
     * A int64 parameter value
     * </pre>
     *
     * <code>repeated int64 int64_values = 6 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The int64Values to set.
     * @return This builder for chaining.
     */
    public Builder setInt64Values(
        int index, long value) {

      ensureInt64ValuesIsMutable();
      int64Values_.setLong(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A int64 parameter value
     * </pre>
     *
     * <code>repeated int64 int64_values = 6 [packed = true];</code>
     * @param value The int64Values to add.
     * @return This builder for chaining.
     */
    public Builder addInt64Values(long value) {

      ensureInt64ValuesIsMutable();
      int64Values_.addLong(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A int64 parameter value
     * </pre>
     *
     * <code>repeated int64 int64_values = 6 [packed = true];</code>
     * @param values The int64Values to add.
     * @return This builder for chaining.
     */
    public Builder addAllInt64Values(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureInt64ValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, int64Values_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A int64 parameter value
     * </pre>
     *
     * <code>repeated int64 int64_values = 6 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64Values() {
      int64Values_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList stringValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureStringValuesIsMutable() {
      if (!stringValues_.isModifiable()) {
        stringValues_ = new com.google.protobuf.LazyStringArrayList(stringValues_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @return A list containing the stringValues.
     */
    public com.google.protobuf.ProtocolStringList
        getStringValuesList() {
      stringValues_.makeImmutable();
      return stringValues_;
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @return The count of stringValues.
     */
    public int getStringValuesCount() {
      return stringValues_.size();
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @param index The index of the element to return.
     * @return The stringValues at the given index.
     */
    public java.lang.String getStringValues(int index) {
      return stringValues_.get(index);
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stringValues at the given index.
     */
    public com.google.protobuf.ByteString
        getStringValuesBytes(int index) {
      return stringValues_.getByteString(index);
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @param index The index to set the value at.
     * @param value The stringValues to set.
     * @return This builder for chaining.
     */
    public Builder setStringValues(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringValuesIsMutable();
      stringValues_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @param value The stringValues to add.
     * @return This builder for chaining.
     */
    public Builder addStringValues(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureStringValuesIsMutable();
      stringValues_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @param values The stringValues to add.
     * @return This builder for chaining.
     */
    public Builder addAllStringValues(
        java.lang.Iterable<java.lang.String> values) {
      ensureStringValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stringValues_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValues() {
      stringValues_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A string parameter value
     * </pre>
     *
     * <code>repeated string string_values = 5;</code>
     * @param value The bytes of the stringValues to add.
     * @return This builder for chaining.
     */
    public Builder addStringValuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureStringValuesIsMutable();
      stringValues_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.DoubleList doubleValues_ = emptyDoubleList();
    private void ensureDoubleValuesIsMutable() {
      if (!doubleValues_.isModifiable()) {
        doubleValues_ = makeMutableCopy(doubleValues_);
      }
      bitField0_ |= 0x00000020;
    }
    private void ensureDoubleValuesIsMutable(int capacity) {
      if (!doubleValues_.isModifiable()) {
        doubleValues_ = makeMutableCopy(doubleValues_, capacity);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <pre>
     * represents a double parameter value.
     * </pre>
     *
     * <code>repeated double double_values = 4 [packed = true];</code>
     * @return A list containing the doubleValues.
     */
    public java.util.List<java.lang.Double>
        getDoubleValuesList() {
      doubleValues_.makeImmutable();
      return doubleValues_;
    }
    /**
     * <pre>
     * represents a double parameter value.
     * </pre>
     *
     * <code>repeated double double_values = 4 [packed = true];</code>
     * @return The count of doubleValues.
     */
    public int getDoubleValuesCount() {
      return doubleValues_.size();
    }
    /**
     * <pre>
     * represents a double parameter value.
     * </pre>
     *
     * <code>repeated double double_values = 4 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The doubleValues at the given index.
     */
    public double getDoubleValues(int index) {
      return doubleValues_.getDouble(index);
    }
    /**
     * <pre>
     * represents a double parameter value.
     * </pre>
     *
     * <code>repeated double double_values = 4 [packed = true];</code>
     * @param index The index to set the value at.
     * @param value The doubleValues to set.
     * @return This builder for chaining.
     */
    public Builder setDoubleValues(
        int index, double value) {

      ensureDoubleValuesIsMutable();
      doubleValues_.setDouble(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * represents a double parameter value.
     * </pre>
     *
     * <code>repeated double double_values = 4 [packed = true];</code>
     * @param value The doubleValues to add.
     * @return This builder for chaining.
     */
    public Builder addDoubleValues(double value) {

      ensureDoubleValuesIsMutable();
      doubleValues_.addDouble(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * represents a double parameter value.
     * </pre>
     *
     * <code>repeated double double_values = 4 [packed = true];</code>
     * @param values The doubleValues to add.
     * @return This builder for chaining.
     */
    public Builder addAllDoubleValues(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureDoubleValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, doubleValues_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * represents a double parameter value.
     * </pre>
     *
     * <code>repeated double double_values = 4 [packed = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearDoubleValues() {
      doubleValues_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bentoml.grpc.v1.Series)
  }

  // @@protoc_insertion_point(class_scope:bentoml.grpc.v1.Series)
  private static final com.bentoml.grpc.v1.Series DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bentoml.grpc.v1.Series();
  }

  public static com.bentoml.grpc.v1.Series getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Series>
      PARSER = new com.google.protobuf.AbstractParser<Series>() {
    @java.lang.Override
    public Series parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Series> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Series> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bentoml.grpc.v1.Series getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

