// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public interface SeriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bentoml.grpc.v1.Series)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A bool parameter value
   * </pre>
   *
   * <code>repeated bool bool_values = 1 [packed = true];</code>
   * @return A list containing the boolValues.
   */
  java.util.List<java.lang.Boolean> getBoolValuesList();
  /**
   * <pre>
   * A bool parameter value
   * </pre>
   *
   * <code>repeated bool bool_values = 1 [packed = true];</code>
   * @return The count of boolValues.
   */
  int getBoolValuesCount();
  /**
   * <pre>
   * A bool parameter value
   * </pre>
   *
   * <code>repeated bool bool_values = 1 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The boolValues at the given index.
   */
  boolean getBoolValues(int index);

  /**
   * <pre>
   * A float parameter value
   * </pre>
   *
   * <code>repeated float float_values = 2 [packed = true];</code>
   * @return A list containing the floatValues.
   */
  java.util.List<java.lang.Float> getFloatValuesList();
  /**
   * <pre>
   * A float parameter value
   * </pre>
   *
   * <code>repeated float float_values = 2 [packed = true];</code>
   * @return The count of floatValues.
   */
  int getFloatValuesCount();
  /**
   * <pre>
   * A float parameter value
   * </pre>
   *
   * <code>repeated float float_values = 2 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The floatValues at the given index.
   */
  float getFloatValues(int index);

  /**
   * <pre>
   * A int32 parameter value
   * </pre>
   *
   * <code>repeated int32 int32_values = 3 [packed = true];</code>
   * @return A list containing the int32Values.
   */
  java.util.List<java.lang.Integer> getInt32ValuesList();
  /**
   * <pre>
   * A int32 parameter value
   * </pre>
   *
   * <code>repeated int32 int32_values = 3 [packed = true];</code>
   * @return The count of int32Values.
   */
  int getInt32ValuesCount();
  /**
   * <pre>
   * A int32 parameter value
   * </pre>
   *
   * <code>repeated int32 int32_values = 3 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The int32Values at the given index.
   */
  int getInt32Values(int index);

  /**
   * <pre>
   * A int64 parameter value
   * </pre>
   *
   * <code>repeated int64 int64_values = 6 [packed = true];</code>
   * @return A list containing the int64Values.
   */
  java.util.List<java.lang.Long> getInt64ValuesList();
  /**
   * <pre>
   * A int64 parameter value
   * </pre>
   *
   * <code>repeated int64 int64_values = 6 [packed = true];</code>
   * @return The count of int64Values.
   */
  int getInt64ValuesCount();
  /**
   * <pre>
   * A int64 parameter value
   * </pre>
   *
   * <code>repeated int64 int64_values = 6 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The int64Values at the given index.
   */
  long getInt64Values(int index);

  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @return A list containing the stringValues.
   */
  java.util.List<java.lang.String>
      getStringValuesList();
  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @return The count of stringValues.
   */
  int getStringValuesCount();
  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @param index The index of the element to return.
   * @return The stringValues at the given index.
   */
  java.lang.String getStringValues(int index);
  /**
   * <pre>
   * A string parameter value
   * </pre>
   *
   * <code>repeated string string_values = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stringValues at the given index.
   */
  com.google.protobuf.ByteString
      getStringValuesBytes(int index);

  /**
   * <pre>
   * represents a double parameter value.
   * </pre>
   *
   * <code>repeated double double_values = 4 [packed = true];</code>
   * @return A list containing the doubleValues.
   */
  java.util.List<java.lang.Double> getDoubleValuesList();
  /**
   * <pre>
   * represents a double parameter value.
   * </pre>
   *
   * <code>repeated double double_values = 4 [packed = true];</code>
   * @return The count of doubleValues.
   */
  int getDoubleValuesCount();
  /**
   * <pre>
   * represents a double parameter value.
   * </pre>
   *
   * <code>repeated double double_values = 4 [packed = true];</code>
   * @param index The index of the element to return.
   * @return The doubleValues at the given index.
   */
  double getDoubleValues(int index);
}
