// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_ServiceMetadataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_ServiceMetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_ServiceMetadataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_DescriptorMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_ServiceMetadataResponse_DescriptorMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_InferenceAPI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_ServiceMetadataResponse_InferenceAPI_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_Part_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_Part_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_Multipart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_Multipart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_Multipart_FieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_Multipart_FieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_File_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_DataFrame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_DataFrame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_Series_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_Series_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bentoml_grpc_v1_NDArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bentoml_grpc_v1_NDArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035bentoml/grpc/v1/service.proto\022\017bentoml" +
      ".grpc.v1\032\034google/protobuf/struct.proto\032\036" +
      "google/protobuf/wrappers.proto\"\030\n\026Servic" +
      "eMetadataRequest\"\336\003\n\027ServiceMetadataResp" +
      "onse\022\014\n\004name\030\001 \001(\t\022C\n\004apis\030\002 \003(\01325.bento" +
      "ml.grpc.v1.ServiceMetadataResponse.Infer" +
      "enceAPI\022\014\n\004docs\030\003 \001(\t\032o\n\022DescriptorMetad" +
      "ata\022\032\n\rdescriptor_id\030\001 \001(\tH\000\210\001\001\022+\n\nattri" +
      "butes\030\002 \001(\0132\027.google.protobuf.StructB\020\n\016" +
      "_descriptor_id\032\360\001\n\014InferenceAPI\022\014\n\004name\030" +
      "\001 \001(\t\022O\n\005input\030\002 \001(\0132;.bentoml.grpc.v1.S" +
      "erviceMetadataResponse.DescriptorMetadat" +
      "aH\000\210\001\001\022P\n\006output\030\003 \001(\0132;.bentoml.grpc.v1" +
      ".ServiceMetadataResponse.DescriptorMetad" +
      "ataH\001\210\001\001\022\021\n\004docs\030\004 \001(\tH\002\210\001\001B\010\n\006_inputB\t\n" +
      "\007_outputB\007\n\005_docs\"\205\003\n\007Request\022\020\n\010api_nam" +
      "e\030\001 \001(\t\022+\n\007ndarray\030\003 \001(\0132\030.bentoml.grpc." +
      "v1.NDArrayH\000\022/\n\tdataframe\030\005 \001(\0132\032.bentom" +
      "l.grpc.v1.DataFrameH\000\022)\n\006series\030\006 \001(\0132\027." +
      "bentoml.grpc.v1.SeriesH\000\022%\n\004file\030\007 \001(\0132\025" +
      ".bentoml.grpc.v1.FileH\000\022,\n\004text\030\010 \001(\0132\034." +
      "google.protobuf.StringValueH\000\022&\n\004json\030\t " +
      "\001(\0132\026.google.protobuf.ValueH\000\022/\n\tmultipa" +
      "rt\030\n \001(\0132\032.bentoml.grpc.v1.MultipartH\000\022\032" +
      "\n\020serialized_bytes\030\002 \001(\014H\000B\t\n\007contentJ\004\010" +
      "\004\020\005J\004\010\013\020\016\"\364\002\n\010Response\022+\n\007ndarray\030\001 \001(\0132" +
      "\030.bentoml.grpc.v1.NDArrayH\000\022/\n\tdataframe" +
      "\030\003 \001(\0132\032.bentoml.grpc.v1.DataFrameH\000\022)\n\006" +
      "series\030\005 \001(\0132\027.bentoml.grpc.v1.SeriesH\000\022" +
      "%\n\004file\030\006 \001(\0132\025.bentoml.grpc.v1.FileH\000\022," +
      "\n\004text\030\007 \001(\0132\034.google.protobuf.StringVal" +
      "ueH\000\022&\n\004json\030\010 \001(\0132\026.google.protobuf.Val" +
      "ueH\000\022/\n\tmultipart\030\t \001(\0132\032.bentoml.grpc.v" +
      "1.MultipartH\000\022\032\n\020serialized_bytes\030\002 \001(\014H" +
      "\000B\t\n\007contentJ\004\010\004\020\005J\004\010\n\020\016\"\306\002\n\004Part\022+\n\007nda" +
      "rray\030\001 \001(\0132\030.bentoml.grpc.v1.NDArrayH\000\022/" +
      "\n\tdataframe\030\003 \001(\0132\032.bentoml.grpc.v1.Data" +
      "FrameH\000\022)\n\006series\030\005 \001(\0132\027.bentoml.grpc.v" +
      "1.SeriesH\000\022%\n\004file\030\006 \001(\0132\025.bentoml.grpc." +
      "v1.FileH\000\022,\n\004text\030\007 \001(\0132\034.google.protobu" +
      "f.StringValueH\000\022&\n\004json\030\010 \001(\0132\026.google.p" +
      "rotobuf.ValueH\000\022\032\n\020serialized_bytes\030\004 \001(" +
      "\014H\000B\020\n\016representationJ\004\010\002\020\003J\004\010\t\020\016\"\211\001\n\tMu" +
      "ltipart\0226\n\006fields\030\001 \003(\0132&.bentoml.grpc.v" +
      "1.Multipart.FieldsEntry\032D\n\013FieldsEntry\022\013" +
      "\n\003key\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.bentoml.grp" +
      "c.v1.Part:\0028\001\"3\n\004File\022\021\n\004kind\030\003 \001(\tH\000\210\001\001" +
      "\022\017\n\007content\030\002 \001(\014B\007\n\005_kind\"K\n\tDataFrame\022" +
      "\024\n\014column_names\030\001 \003(\t\022(\n\007columns\030\002 \003(\0132\027" +
      ".bentoml.grpc.v1.Series\"\241\001\n\006Series\022\027\n\013bo" +
      "ol_values\030\001 \003(\010B\002\020\001\022\030\n\014float_values\030\002 \003(" +
      "\002B\002\020\001\022\030\n\014int32_values\030\003 \003(\005B\002\020\001\022\030\n\014int64" +
      "_values\030\006 \003(\003B\002\020\001\022\025\n\rstring_values\030\005 \003(\t" +
      "\022\031\n\rdouble_values\030\004 \003(\001B\002\020\001\"\302\003\n\007NDArray\022" +
      "-\n\005dtype\030\001 \001(\0162\036.bentoml.grpc.v1.NDArray" +
      ".DType\022\r\n\005shape\030\002 \003(\005\022\025\n\rstring_values\030\005" +
      " \003(\t\022\030\n\014float_values\030\003 \003(\002B\002\020\001\022\031\n\rdouble" +
      "_values\030\004 \003(\001B\002\020\001\022\027\n\013bool_values\030\006 \003(\010B\002" +
      "\020\001\022\030\n\014int32_values\030\007 \003(\005B\002\020\001\022\030\n\014int64_va" +
      "lues\030\010 \003(\003B\002\020\001\022\031\n\ruint32_values\030\t \003(\rB\002\020" +
      "\001\022\031\n\ruint64_values\030\n \003(\004B\002\020\001\"\251\001\n\005DType\022\025" +
      "\n\021DTYPE_UNSPECIFIED\020\000\022\017\n\013DTYPE_FLOAT\020\001\022\020" +
      "\n\014DTYPE_DOUBLE\020\002\022\016\n\nDTYPE_BOOL\020\003\022\017\n\013DTYP" +
      "E_INT32\020\004\022\017\n\013DTYPE_INT64\020\005\022\020\n\014DTYPE_UINT" +
      "32\020\006\022\020\n\014DTYPE_UINT64\020\007\022\020\n\014DTYPE_STRING\020\010" +
      "2\265\001\n\014BentoService\022=\n\004Call\022\030.bentoml.grpc" +
      ".v1.Request\032\031.bentoml.grpc.v1.Response\"\000" +
      "\022f\n\017ServiceMetadata\022\'.bentoml.grpc.v1.Se" +
      "rviceMetadataRequest\032(.bentoml.grpc.v1.S" +
      "erviceMetadataResponse\"\000B]\n\023com.bentoml." +
      "grpc.v1B\014ServiceProtoP\001Z*github.com/bent" +
      "oml/bentoml/grpc/v1;service\220\001\001\370\001\001\242\002\003SVCb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_bentoml_grpc_v1_ServiceMetadataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bentoml_grpc_v1_ServiceMetadataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_ServiceMetadataRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_ServiceMetadataResponse_descriptor,
        new java.lang.String[] { "Name", "Apis", "Docs", });
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_DescriptorMetadata_descriptor =
      internal_static_bentoml_grpc_v1_ServiceMetadataResponse_descriptor.getNestedTypes().get(0);
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_DescriptorMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_ServiceMetadataResponse_DescriptorMetadata_descriptor,
        new java.lang.String[] { "DescriptorId", "Attributes", "DescriptorId", });
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_InferenceAPI_descriptor =
      internal_static_bentoml_grpc_v1_ServiceMetadataResponse_descriptor.getNestedTypes().get(1);
    internal_static_bentoml_grpc_v1_ServiceMetadataResponse_InferenceAPI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_ServiceMetadataResponse_InferenceAPI_descriptor,
        new java.lang.String[] { "Name", "Input", "Output", "Docs", "Input", "Output", "Docs", });
    internal_static_bentoml_grpc_v1_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bentoml_grpc_v1_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_Request_descriptor,
        new java.lang.String[] { "ApiName", "Ndarray", "Dataframe", "Series", "File", "Text", "Json", "Multipart", "SerializedBytes", "Content", });
    internal_static_bentoml_grpc_v1_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bentoml_grpc_v1_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_Response_descriptor,
        new java.lang.String[] { "Ndarray", "Dataframe", "Series", "File", "Text", "Json", "Multipart", "SerializedBytes", "Content", });
    internal_static_bentoml_grpc_v1_Part_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bentoml_grpc_v1_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_Part_descriptor,
        new java.lang.String[] { "Ndarray", "Dataframe", "Series", "File", "Text", "Json", "SerializedBytes", "Representation", });
    internal_static_bentoml_grpc_v1_Multipart_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bentoml_grpc_v1_Multipart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_Multipart_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_bentoml_grpc_v1_Multipart_FieldsEntry_descriptor =
      internal_static_bentoml_grpc_v1_Multipart_descriptor.getNestedTypes().get(0);
    internal_static_bentoml_grpc_v1_Multipart_FieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_Multipart_FieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_bentoml_grpc_v1_File_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_bentoml_grpc_v1_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_File_descriptor,
        new java.lang.String[] { "Kind", "Content", "Kind", });
    internal_static_bentoml_grpc_v1_DataFrame_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_bentoml_grpc_v1_DataFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_DataFrame_descriptor,
        new java.lang.String[] { "ColumnNames", "Columns", });
    internal_static_bentoml_grpc_v1_Series_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_bentoml_grpc_v1_Series_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_Series_descriptor,
        new java.lang.String[] { "BoolValues", "FloatValues", "Int32Values", "Int64Values", "StringValues", "DoubleValues", });
    internal_static_bentoml_grpc_v1_NDArray_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_bentoml_grpc_v1_NDArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bentoml_grpc_v1_NDArray_descriptor,
        new java.lang.String[] { "Dtype", "Shape", "StringValues", "FloatValues", "DoubleValues", "BoolValues", "Int32Values", "Int64Values", "Uint32Values", "Uint64Values", });
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
