// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public interface ServiceMetadataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bentoml.grpc.v1.ServiceMetadataRequest)
    com.google.protobuf.MessageOrBuilder {
}
