// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bentoml/grpc/v1/service.proto

package com.bentoml.grpc.v1;

public interface ServiceMetadataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bentoml.grpc.v1.ServiceMetadataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name is the service name.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * name is the service name.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * apis holds a list of InferenceAPI of the service.
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPI apis = 2;</code>
   */
  java.util.List<com.bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPI> 
      getApisList();
  /**
   * <pre>
   * apis holds a list of InferenceAPI of the service.
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPI apis = 2;</code>
   */
  com.bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPI getApis(int index);
  /**
   * <pre>
   * apis holds a list of InferenceAPI of the service.
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPI apis = 2;</code>
   */
  int getApisCount();
  /**
   * <pre>
   * apis holds a list of InferenceAPI of the service.
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPI apis = 2;</code>
   */
  java.util.List<? extends com.bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPIOrBuilder> 
      getApisOrBuilderList();
  /**
   * <pre>
   * apis holds a list of InferenceAPI of the service.
   * </pre>
   *
   * <code>repeated .bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPI apis = 2;</code>
   */
  com.bentoml.grpc.v1.ServiceMetadataResponse.InferenceAPIOrBuilder getApisOrBuilder(
      int index);

  /**
   * <pre>
   * docs is the documentation of the service.
   * </pre>
   *
   * <code>string docs = 3;</code>
   * @return The docs.
   */
  java.lang.String getDocs();
  /**
   * <pre>
   * docs is the documentation of the service.
   * </pre>
   *
   * <code>string docs = 3;</code>
   * @return The bytes for docs.
   */
  com.google.protobuf.ByteString
      getDocsBytes();
}
