api_server:
  http:
    port: 3100
  # grpc:
  #   host: 0.0.0.0
  #   port: 3100
  metrics:
    enabled: false
runners:
  batching:
    enabled: false
    # max_batch_size: 1000
    # max_latency_ms: 200
