api_server:
  grpc:
    port: 3000
    reflection:
      enabled: true
  logging:
    access:
      enabled: true
      request_content_length: true
      # whether to log the content type of the request
      request_content_type: true
      # whether to log the content length of the response
      response_content_length: true
      # whether to log the content type of the response
      response_content_type: true
runners:
  logging:
    access:
      enabled: true
tracing:
  exporter_type: jaeger
  sample_rate: 1.0
  jaeger:
    address: localhost
    port: 6831
  excluded_urls: readyz,livez,healthz,static_content,docs,metrics