version: '3'
networks:
  my_network:
    driver: bridge
services:
  backend:
    image: hieungo1898/back-end:latest #service_predictor:latest #hieungo1898/back-end:latest
    ports:
      - 5040:5040
    networks:
      - my_network
  predictor:
    image: service1:2ygshoroc2o5uexp
    environment:
      - BENTOML_CONFIG=./src/bentoml_configuration.yml
    command: serve
    ports:
      - 3000:3000
    networks:
      - my_network
  predictor2:
    image: model2:7frifaroc6fjmexp
    environment:
      - BENTOML_CONFIG=./src/bentoml_configuration2.yml
    command: serve
    ports:
      - 3100:3100
    networks:
      - my_network
  
  # predictor:
  #   image: hieungo1898/bento-serviceall:latest
  #   command: serve
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - my_network
  
  
  
  # python_service:
  #   image: python_service:${IMAGE_TAG}
  #   ports:
  #     - 3000:3000
  #   environment:
  #     MLFLOW_TRACKING_URI: http://host.docker.internal:5001
  #   networks:
  #     - my_network
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   entrypoint: /bin/sh -c "ls && cd src && bentoml serve-grpc service2.py:svc"

